"""Combine gen_pyerr_tables.py outputs (darwin.json linux.json) into lcu/compat/pyerr_tables.mjs.

usage: build_pyerr_tables.py darwin.json linux.json > lcu/compat/pyerr_tables.mjs
"""
import json
import sys

print('// Generated by tests/compat/gen_pyerr_tables.py on each platform (Python 3.12; darwin libc, glibc).')
print('// Do not edit by hand; tests/compat/test_pyerr.py checks these against the live interpreter.')
for plat, path in (('darwin', sys.argv[1]), ('linux', sys.argv[2])):
    with open(path) as stream:
        data = json.load(stream)
    known = {k: v for k, v in data['strerror'].items() if not v.startswith('Unknown error')}
    table = {'errno': data['errno'], 'strerror': known, 'signals': data['signals'],
             'unknown': data['strerror']['199'].replace('199', '%d')}
    print(f'export const {plat} = Object.freeze({json.dumps(table, sort_keys=True, indent=1)});')

sys.path.insert(0, __import__('os').path.dirname(__file__))
from gen_printable_table import table  # noqa: E402

print(table())
