"""Regenerate lcu/compat/pyctype_tables.mjs: code point ranges of CPython's character predicates.

Python's `re` (str patterns) and str methods use this interpreter's Unicode database (3.12: Unicode 15.0), while
JavaScript's \\p{...} classes follow the running Node's ICU (Node 24: Unicode 16). LCU code whose accepted
inputs are defined by Python regexes uses these frozen tables instead.
  DECIMAL  re `\\d` / str.isdecimal()
  WORD     re `\\w` (str.isalnum() or '_')
  ALPHA    str.isalpha()
  SPACE    re `\\s` / str.isspace()
Run: python3 tests/compat/gen_pyctype_tables.py
"""
import re
import sys
import unicodedata
from pathlib import Path


def ranges(predicate):
    out = []
    start = None
    for cp in range(0x110000):
        ok = predicate(chr(cp))
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def main():
    word = re.compile(r'\w')
    digit = re.compile(r'\d')
    space = re.compile(r'\s')
    tables = {
        'DECIMAL': ranges(lambda c: digit.match(c) is not None),
        'WORD': ranges(lambda c: word.match(c) is not None),
        'ALPHA': ranges(str.isalpha),
        'SPACE': ranges(lambda c: space.match(c) is not None),
    }
    assert ranges(str.isspace) == tables['SPACE']
    lines = [f'// GENERATED by tests/compat/gen_pyctype_tables.py from CPython {sys.version.split()[0]} '
             f'(Unicode {unicodedata.unidata_version}). Do not edit.',
             '// Inclusive code point ranges, flattened [lo, hi, lo, hi, ...].',
             f"export const UNICODE_VERSION = '{unicodedata.unidata_version}';"]
    for name, table in tables.items():
        flat = ','.join(f'{a},{b}' for a, b in table)
        lines.append(f'export const {name} = [{flat}];')
    lines.append('')
    Path(__file__).resolve().parents[2].joinpath('lcu/compat/pyctype_tables.mjs').write_text('\n'.join(lines))
    print({k: len(v) for k, v in tables.items()})


if __name__ == '__main__':
    main()
