"""Regenerate lcu/compat/appx_xml_tables.mjs from the expat bundled with this Python (xml.etree).

Expat's NameStartChar / NameChar classes follow the XML 1.0 fourth edition tables (no astral characters, no
U+2C00-U+2FEF ...), so they are probed rather than hand-written. Run: python3 tests/compat/gen_xml_name_tables.py
"""
import sys
import xml.etree.ElementTree as ET
from pathlib import Path


def valid(source):
    try:
        ET.fromstring(source)
        return True
    except ET.ParseError:
        return False


def ranges(predicate):
    out = []
    start = None
    for cp in range(0x110000):
        ok = predicate(cp) if not 0xD800 <= cp <= 0xDFFF else False
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, 0x10FFFF))
    return out


def main():
    start = ranges(lambda cp: cp != 0x3A and cp < 0x10000 and valid(f'<{chr(cp)}a></{chr(cp)}a>'))
    body = ranges(lambda cp: cp != 0x3A and cp < 0x10000 and valid(f'<a{chr(cp)}b></a{chr(cp)}b>'))
    # Probe a sample of astral code points to document that expat accepts none of them.
    for cp in (0x10000, 0x1F600, 0xE0000, 0xEFFFF):
        assert not valid(f'<{chr(cp)}a></{chr(cp)}a>') and not valid(f'<a{chr(cp)}b></a{chr(cp)}b>'), hex(cp)
    text = ['// Generated by tests/compat/gen_xml_name_tables.py from the expat bundled with CPython '
            f'{sys.version.split()[0]}.', '// Code point ranges (inclusive) accepted by expat as XML name start / name characters',
            '// (":" excluded: handled by the parser).', '',
            'export const NAME_START_RANGES = [' + ', '.join(f'[0x{a:x}, 0x{b:x}]' for a, b in start) + '];',
            '',
            'export const NAME_CHAR_RANGES = [' + ', '.join(f'[0x{a:x}, 0x{b:x}]' for a, b in body) + '];', '']
    Path(__file__).resolve().parents[2].joinpath('lcu/compat/appx_xml_tables.mjs').write_text('\n'.join(text))
    print(len(start), len(body))


if __name__ == '__main__':
    main()
