"""Generate lcu/compat/unicode_tables.mjs: Python 3.12's str.casefold() for every code point that changes."""
import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / 'lcu' / 'compat' / 'unicode_tables.mjs'


def main():
    if sys.version_info[:2] != (3, 12):
        sys.exit('run with Python 3.12 so the tables match the release the port replaces')
    rows = []
    for cp in range(0x110000):
        char = chr(cp)
        folded = char.casefold()
        if folded != char:
            rows.append(f'{cp:X}={" ".join(f"{ord(c):X}" for c in folded)}')
    OUT.write_text(
        '// GENERATED by tests/compat/gen_unicode_tables.py from Python %s (Unicode %s). Do not edit.\n'
        '// One "<code point hex>=<folded code points hex, space separated>" entry per line: every code point\n'
        '// whose str.casefold() differs from itself (CaseFolding.txt statuses C and F).\n'
        'export const UNICODE_VERSION = %r;\n'
        'export const CASEFOLD = `\n%s\n`;\n' % (sys.version.split()[0], unicodedata.unidata_version,
                                               unicodedata.unidata_version, '\n'.join(rows)))
    print(f'{len(rows)} entries -> {OUT}')


if __name__ == '__main__':
    main()
