"""Regenerate lcu/compat/pycodecs_tables.mjs from this CPython (3.12) build.

Two consumers:
  * lcu/compat/appx_xml.mjs: pyexpat's unknown-encoding handler (PyUnicode_Decode(bytes(range(256)), name,
    'replace'), length must be 256, U+FFFD marks an invalid byte) and expat's acceptance of that map;
  * lcu/compat/pycodecs.mjs: strict decoding with single-byte 'charmap' codecs (Windows ANSI code pages), where
    exactly the bytes mapped to U+FFFD here fail.
Run: python3 tests/compat/gen_pycodecs_tables.py
"""
import codecs
import encodings
import encodings.aliases
import io
import json
import pkgutil
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

TEMPLATE = bytes(range(256))


def outcome(name):
    try:
        # PyUnicode_Decode() goes through the text-encoding lookup first (LookupError for bytes codecs).
        info = codecs.lookup(name)
        if not info._is_text_encoding:
            return {'kind': 'error', 'class': 'LookupError',
                    'message': "'{name}' is not a text encoding; use codecs.decode() to handle arbitrary codecs"}
        text = TEMPLATE.decode(name, 'replace')
    except LookupError:
        return {'kind': 'error', 'class': 'LookupError', 'message': 'unknown encoding: {name}'}
    except Exception as exc:  # noqa: BLE001 - recorded verbatim
        return {'kind': 'error', 'class': type(exc).__name__, 'message': str(exc)}
    if len(text) != 256:
        return {'kind': 'error', 'class': 'ValueError', 'message': 'multi-byte encodings are not supported'}
    try:
        ET.parse(io.BytesIO(f'<?xml version="1.0" encoding="{name}"?><a/>'.encode('ascii')))
        expat = True
    except ET.ParseError:
        expat = False
    except Exception:  # noqa: BLE001
        expat = None
    return {'kind': 'map', 'map': text, 'expat': expat, 'codec': codecs.lookup(name).name}


def main():
    modules = sorted({m.name for m in pkgutil.iter_modules(encodings.__path__)} |
                     set(encodings.aliases.aliases.values()))
    table = {}
    for module in modules:
        if module in ('aliases',):
            continue
        result = outcome(module)
        if result['kind'] == 'error' and result['message'] == 'unknown encoding: {name}':
            continue
        table[module] = result
    aliases = {alias: module for alias, module in encodings.aliases.aliases.items() if module in table}
    lines = [f'// GENERATED by tests/compat/gen_pycodecs_tables.py from CPython {sys.version.split()[0]} '
             f'on {sys.platform}. Do not edit.',
             '// ALIASES: encodings.aliases (normalized alias -> codec module).',
             '// CODECS: module -> {kind: "map", map: <256 chars, U+FFFD = invalid byte>, expat: <expat accepts the',
             '//   map>, codec: <CodecInfo.name>}',
             '//   or {kind: "error", class, message} raised by pyexpat\'s handler ({name} = the declared name).',
             f'export const ALIASES = {json.dumps(aliases, sort_keys=True)};',
             f'export const CODECS = {json.dumps(table, sort_keys=True, ensure_ascii=True)};', '']
    Path(__file__).resolve().parents[2].joinpath('lcu/compat/pycodecs_tables.mjs').write_text('\n'.join(lines))
    print(len(table), 'codecs', len(aliases), 'aliases')


if __name__ == '__main__':
    main()
