// Regex character classes for CPython 3.12's `\d`, `\w`, `\s` and str.isalpha(), frozen from Python's Unicode
// database (pyctype_tables.mjs, generated by tests/compat/gen_pyctype_tables.py) so acceptance does not change
// with the Unicode version of the running Node. Use the class bodies inside `[...]` with the `u` flag.
import { ALPHA, DECIMAL, SPACE, WORD } from './pyctype_tables.mjs';

const esc = (cp) => `\\u{${cp.toString(16)}}`;

function body(flat) {
  let out = '';
  for (let i = 0; i < flat.length; i += 2) out += flat[i] === flat[i + 1] ? esc(flat[i]) : `${esc(flat[i])}-${esc(flat[i + 1])}`;
  return out;
}

/** Class bodies (without brackets), for RegExp(..., 'u'). */
export const PY_DECIMAL = body(DECIMAL);
export const PY_WORD = body(WORD);
export const PY_ALPHA = body(ALPHA);
export const PY_SPACE = body(SPACE);

const SPACE_RE = new RegExp(`^[${PY_SPACE}]$`, 'u');
const ALPHA_RE = new RegExp(`^[${PY_ALPHA}]$`, 'u');

/** str.isspace() for one character. */
export const isspace = (ch) => SPACE_RE.test(ch);
/** str.isalpha() for one character (code point). */
export const isalpha = (ch) => ALPHA_RE.test(ch);
