// Port of tests/test_browser_setup.py (+ test_runtime.py's browser-foreign-directory case) and the relay migration.
// Native-host setup tests use only disposable homes and a fake upstream installer. Run with
// `node --test tests/node/browser.test.mjs`.
import { python312 } from './runtime_support.mjs';
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import {
  chmodSync, existsSync, utimesSync, lstatSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, realpathSync, rmSync,
  statSync, symlinkSync, unlinkSync, renameSync, writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { after, afterEach, beforeEach, describe, it } from 'node:test';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { Worker } from 'node:worker_threads';

import * as browser from '../../lcu/browser.mjs';
import { skipOnWindows } from './windows_skip.mjs';
const RELAY_CLOSURE = browser._relay_implementation(fileURLToPath(new URL('../..', import.meta.url)).replace(/[\\/]$/, ''));
import { io, PySystemExit } from '../../lcu/compat/argparse.mjs';
import { ORACLE_ROOT } from './oracle_root.mjs';

const ROOT = dirname(dirname(dirname(fileURLToPath(import.meta.url))));
const PYTHON = python312() ?? undefined; // exactly CPython 3.12.10 (never a PATH python3: 3.12.3 and 3.14 word argparse differently)
const temporaries = [];
after(() => { for (const dir of temporaries) rmSync(dir, { recursive: true, force: true }); });
const scratch = () => {
  const dir = realpathSync.native(mkdtempSync(join(tmpdir(), 'lcu-browser-'))); // native: the product resolves 8.3 names
  temporaries.push(dir);
  return dir;
};

const completed = (returncode = 0, stdout = '', stderr = '') => ({ args: [], returncode, stdout, stderr });

const POSIX_LAUNCHER = (lcu, directory) => '#!/bin/sh\n'
  + '# LCU Chrome native-host relay (generated by `lcu browser install`). Writes nothing on stdout itself:\n'
  + '# the stable LCU launcher applies the pre-Node gate and environment quarantine, then runs the relay.\n'
  + `_lcu=${shq(lcu)}\n`
  + 'if [ ! -f "$_lcu" ] || [ ! -x "$_lcu" ]; then\n'
  + '  printf \'LCU Chrome native-host relay: %s is missing; reinstall LCU, then run `lcu browser install`.\\n\' "$_lcu" >&2\n'
  + '  exit 1\n'
  + 'fi\n'
  + `exec "$_lcu" browser __native-host ${shq(directory)} "$@"\n`;
const WINDOWS_CMD = (lcu) => `@echo off\r\nif not exist "${lcu}" (\r\n`
  + `  >&2 echo LCU Chrome native-host relay: ${lcu} is missing; reinstall LCU, then run lcu browser install.\r\n`
  + '  exit /b 1\r\n)\r\n'
  + `call "${lcu}" browser __native-host "%~dp0." %*\r\nexit /b %ERRORLEVEL%\r\n`;
function shq(text) {
  return /^[A-Za-z0-9_@%+=:,./-]+$/.test(text) ? text : `'${text.replaceAll("'", `'"'"'`)}'`;
}

/** Install the relay source files of the real release into a fixture root. */
function releaseRelay(root) {
  for (const relative of RELAY_CLOSURE) {
    mkdirSync(dirname(join(root, relative)), { recursive: true });
    writeFileSync(join(root, relative), readFileSync(join(ROOT, relative)));
  }
}

const saved = { ...browser.hooks };
const savedEnv = { ...process.env };
function patch(values, env = {}) {
  Object.assign(browser.hooks, values);
  Object.assign(process.env, env);
}
function restore() {
  for (const key of Object.keys(browser.hooks)) browser.hooks[key] = saved[key];
  for (const key of Object.keys(process.env)) if (!(key in savedEnv)) delete process.env[key];
  Object.assign(process.env, savedEnv);
}

function capture(fn) {
  let out = '';
  const real = io.stdout;
  io.stdout = (text) => { out += text; };
  try { return [fn(), out]; } finally { io.stdout = real; }
}

describe('BrowserSetupTests', () => {
  afterEach(restore);

  it('windows original installer and registry are reused for cmd relay', () => {
    const base = scratch();
    const root = join(base, 'release');
    const app = join(base, 'registered-msix');
    const resources = join(app, 'app/resources');
    const plugin = join(resources, 'plugins/openai-bundled/plugins/chrome');
    mkdirSync(join(plugin, 'scripts'), { recursive: true });
    writeFileSync(join(plugin, 'scripts/installManifest.mjs'), 'upstream fixture');
    const host = join(plugin, 'extension-host/windows/x64/extension-host.exe');
    mkdirSync(dirname(host), { recursive: true });
    writeFileSync(host, 'original executable fixture');
    releaseRelay(root);
    const home = join(base, 'account');
    mkdirSync(home);
    const local = join(home, 'AppData/Local');
    const manifest = join(local, 'OpenAI/extension/com.openai.codexextension.json');
    const env = { USERPROFILE: home, LOCALAPPDATA: local, NODE_REPL_NODE_PATH: 'C:/node.exe',
      CODEX_CLI_PATH: 'C:/codex.exe', CUA_REPL_NODE_REPL_PATH: 'C:/node_repl.exe' };
    const calls = [];
    const original = (command) => {
      calls.push(command);
      if (command[0] === 'reg.exe') return completed(0, `${manifest} REG_SZ ${manifest}`);
      const privateDir = join(join(local, 'lcu/browser'), readdirSync(join(local, 'lcu/browser')).find((d) => statSync(join(local, 'lcu/browser', d)).isDirectory()), 'chrome');
      mkdirSync(dirname(manifest), { recursive: true });
      writeFileSync(manifest, JSON.stringify({ name: 'com.openai.codexextension',
        path: join(privateDir, 'extension-host/windows/x64/extension-host.exe'), allowed_origins: ['chrome-extension://fixture/'] }));
      return completed(0);
    };
    patch({
      system: () => 'Windows', paths: () => [app, resources, null, {}], environment: () => env,
      capture_run: original, run: original, stable_lcu: () => 'C:\\LCU\\lcu.cmd',
    }, { USERPROFILE: home, LOCALAPPDATA: local });
    const destination = browser.install(root);
    const configured = JSON.parse(readFileSync(manifest, 'utf8'));
    assert.equal(configured.path, join(destination, 'lcu-native-host.cmd'));
    assert.deepEqual(configured.allowed_origins, ['chrome-extension://fixture/']);
    const command = readFileSync(join(destination, 'lcu-native-host.cmd'));
    assert.ok(command.includes('@echo off'));
    assert.equal(command.toString(), WINDOWS_CMD('C:\\LCU\\lcu.cmd'));
    assert.equal(readFileSync(join(destination, '.lcu-browser-host'), 'utf8'), `${app}${process.platform === 'win32' ? '\r\n' : '\n'}`); // text mode
    assert.equal(calls.length, 2);
  });

  it('macos manifest locations match original installer', { skip: skipOnWindows('macOS Chrome manifest locations and rewrite (Library/Application Support under HOME); never runs on Windows') }, () => {
    const home = '/private/tmp/disposable-home';
    const found = browser._manifest_paths({ HOME: home }, 'Darwin');
    assert.equal(found.size, 8);
    for (const browserDir of ['Google/Chrome', 'Microsoft Edge', 'BraveSoftware/Brave-Browser']) {
      assert.ok(found.has(`${home}/Library/Application Support/${browserDir}/NativeMessagingHosts/com.openai.codexextension.json`));
    }
  });

  function macFixture(base, { installer = 'fixture' } = {}) {
    const root = join(base, 'release');
    const home = join(base, 'home');
    const resources = join(root, 'app/Contents/Resources');
    const source = join(resources, 'plugins/openai-bundled/plugins/chrome');
    mkdirSync(join(source, 'scripts'), { recursive: true });
    writeFileSync(join(source, 'scripts/installManifest.mjs'), installer);
    const host = join(source, 'extension-host/macos/arm64/ChatGPT for Chrome');
    mkdirSync(dirname(host), { recursive: true });
    writeFileSync(host, 'fixture');
    releaseRelay(root);
    mkdirSync(home);
    const env = { HOME: home, NODE_REPL_NODE_PATH: '/fake/node', CODEX_CLI_PATH: '/fake/codex', CUA_REPL_NODE_REPL_PATH: '/fake/repl' };
    return { root, home, resources, source, host, env };
  }

  it('macos setup rewrites only manifests for selected original host', { skip: skipOnWindows('macOS Chrome manifest locations and rewrite (Library/Application Support under HOME); never runs on Windows') }, () => {
    const { root, home, resources, env } = macFixture(scratch());
    const support = join(home, 'Library/Application Support');
    const chrome = join(support, 'Google/Chrome/NativeMessagingHosts/com.openai.codexextension.json');
    const edge = join(support, 'Microsoft Edge/NativeMessagingHosts/com.openai.codexextension.json');
    const unrelated = join(support, 'BraveSoftware/Brave-Browser/NativeMessagingHosts/com.openai.codexextension.json');
    const calls = [];
    const installer = (args) => {
      calls.push(args);
      const destinations = join(support, 'lcu/browser');
      const plugin = join(destinations, readdirSync(destinations).find((d) => statSync(join(destinations, d)).isDirectory()), 'chrome');
      const selectedHost = join(plugin, 'extension-host/macos/arm64/ChatGPT for Chrome');
      for (const [path, selected] of [[chrome, selectedHost], [edge, selectedHost], [unrelated, '/other/ChatGPT for Chrome']]) {
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, JSON.stringify({ name: 'com.openai.codexextension', path: selected, allowed_origins: ['chrome-extension://fixture/'] }));
      }
      return completed(0);
    };
    patch({ system: () => 'Darwin', paths: () => [join(root, 'app'), resources, null, {}], environment: () => env, capture_run: installer }, { HOME: home });
    const destination = browser.install(root);
    const expectedRelay = join(destination, 'lcu-native-host');
    assert.equal(JSON.parse(readFileSync(chrome, 'utf8')).path, expectedRelay);
    assert.equal(JSON.parse(readFileSync(edge, 'utf8')).path, expectedRelay);
    assert.equal(JSON.parse(readFileSync(unrelated, 'utf8')).path, '/other/ChatGPT for Chrome');
    assert.deepEqual(JSON.parse(readFileSync(chrome, 'utf8')).allowed_origins, ['chrome-extension://fixture/']);
    // json.dump(manifest, indent=2) + '\n', mode 0644, key order kept
    assert.equal(readFileSync(chrome, 'utf8'), `{\n  "name": "com.openai.codexextension",\n  "path": ${JSON.stringify(expectedRelay)},\n  "allowed_origins": [\n    "chrome-extension://fixture/"\n  ]\n}\n`);
    assert.equal(statSync(chrome).mode & 0o777, 0o644);
    assert.equal(readFileSync(join(destination, '.lcu-browser-host'), 'utf8'), `${realpathSync(join(root, 'app'))}\n`);
    assert.equal(statSync(expectedRelay).mode & 0o777, 0o700);
    assert.equal(calls.length, 1);
    assert.equal(calls[0][0], '/fake/node');
    assert.ok(existsSync(join(destination, 'chrome/scripts/installManifest.mjs')));
  });

  it('same path app upgrade refreshes the private plugin copy', () => {
    const { root, home, resources, source, host, env } = macFixture(scratch(), { installer: 'version one' });
    writeFileSync(host, 'host one');
    const manifest = join(home, 'Library/Application Support/Google/Chrome/NativeMessagingHosts/com.openai.codexextension.json');
    const installer = () => {
      const destinations = join(home, 'Library/Application Support/lcu/browser');
      const privateDir = join(destinations, readdirSync(destinations).find((d) => statSync(join(destinations, d)).isDirectory()), 'chrome');
      mkdirSync(dirname(manifest), { recursive: true });
      writeFileSync(manifest, JSON.stringify({ path: join(privateDir, 'extension-host/macos/arm64/ChatGPT for Chrome') }));
      return completed(0);
    };
    patch({ system: () => 'Darwin', paths: () => [join(root, 'app'), resources, null, {}], environment: () => env, capture_run: installer }, { HOME: home });
    const first = browser.install(root);
    assert.equal(readFileSync(join(first, 'chrome/scripts/installManifest.mjs'), 'utf8'), 'version one');
    const unchanged = statSync(join(first, 'chrome')).ino;
    assert.equal(browser.install(root), first);
    assert.equal(statSync(join(first, 'chrome')).ino, unchanged);
    writeFileSync(join(source, 'scripts/installManifest.mjs'), 'version two'); // apt upgrade at the same path
    writeFileSync(host, 'host two');
    const second = browser.install(root);
    assert.equal(second, first);
    assert.equal(readFileSync(join(second, 'chrome/scripts/installManifest.mjs'), 'utf8'), 'version two');
    assert.equal(readFileSync(join(second, 'chrome/extension-host/macos/arm64/ChatGPT for Chrome'), 'utf8'), 'host two');
    assert.deepEqual(new Set(readdirSync(second)),
      new Set(['chrome', 'lcu-native-host', '.lcu-relay-implementation', '.lcu-browser-host', '.lcu-browser-plugin']));
  });

  it('macos missing original manifest fails', () => {
    const { root, home, resources, env } = macFixture(scratch());
    patch({ system: () => 'Darwin', paths: () => [join(root, 'app'), resources, null, {}], environment: () => env, capture_run: () => completed(0) }, { HOME: home });
    assert.throws(() => browser.install(root), (e) => e.name === 'ValueError' && /produced no manifest/.test(e.message));
  });

  it('original installer failure surfaces stderr', () => {
    const { root, home, resources, env } = macFixture(scratch());
    patch({ system: () => 'Darwin', paths: () => [join(root, 'app'), resources, null, {}], environment: () => env,
      capture_run: () => completed(1, '', 'installer exploded') }, { HOME: home });
    assert.throws(() => browser.install(root), (e) => e.name === 'ValueError'
      && e.message === 'The original Chrome installer failed (exit 1). installer exploded');
  });

  it('browser setup refuses foreign directory (test_runtime.py)', () => {
    const root = scratch();
    mkdirSync(join(root, 'host/plugins/chrome/scripts'), { recursive: true });
    writeFileSync(join(root, 'host/plugins/chrome/scripts/installManifest.mjs'), 'upstream fixture');
    const foreign = join(root, 'foreign');
    mkdirSync(foreign);
    writeFileSync(join(foreign, 'keep'), 'existing data');
    patch({ system: () => 'Darwin' });
    assert.throws(() => browser.install(root, foreign), (e) => /another installation/.test(e.message));
    assert.equal(readFileSync(join(foreign, 'keep'), 'utf8'), 'existing data');
  });

  it('a symlinked host directory and a missing release relay are refused', () => {
    const { root, home, resources, env } = macFixture(scratch());
    patch({ system: () => 'Darwin', paths: () => [join(root, 'app'), resources, null, {}], environment: () => env, capture_run: () => completed(0) }, { HOME: home });
    const link = join(home, 'link');
    symlinkSync(home, link);
    assert.throws(() => browser.install(root, link), (e) => e.message === 'The browser host directory must not be a symlink.');
    unlinkSync(join(root, 'lcu/native_host.mjs'));
    assert.throws(() => browser.install(root, join(home, 'fresh')), (e) => e.message === 'The LCU Chrome native-host relay is missing from this release.');
  });
});

describe('PluginCopyRefreshTests', () => {
  // The private Chrome plugin copy and its digest are published together and recoverable.
  let root; let home; let source; let installer; let destinations;

  beforeEach(() => {
    const base = scratch();
    root = join(base, 'release');
    home = join(base, 'home');
    mkdirSync(home);
    const resources = join(root, 'app/Contents/Resources');
    source = join(resources, 'plugins/openai-bundled/plugins/chrome');
    mkdirSync(join(source, 'scripts'), { recursive: true });
    installer = join(source, 'scripts/installManifest.mjs');
    writeFileSync(installer, 'version one');
    const host = join(source, 'extension-host/macos/arm64/ChatGPT for Chrome');
    mkdirSync(dirname(host), { recursive: true });
    writeFileSync(host, 'host');
    releaseRelay(root);
    const support = join(home, 'Library/Application Support');
    destinations = join(support, 'lcu/browser');
    const manifest = join(support, 'Google/Chrome/NativeMessagingHosts/com.openai.codexextension.json');
    const env = { HOME: home, NODE_REPL_NODE_PATH: '/fake/node', CODEX_CLI_PATH: '/fake/codex', CUA_REPL_NODE_REPL_PATH: '/fake/repl' };
    const original = () => {
      const privateDir = join(destinations, readdirSync(destinations).find((d) => statSync(join(destinations, d)).isDirectory()), 'chrome');
      mkdirSync(dirname(manifest), { recursive: true });
      writeFileSync(manifest, JSON.stringify({ path: join(privateDir, 'extension-host/macos/arm64/ChatGPT for Chrome') }));
      return completed(0);
    };
    patch({ system: () => 'Darwin', paths: () => [join(root, 'app'), resources, null, {}], environment: () => env, capture_run: original }, { HOME: home });
  });
  afterEach(restore);

  const privateCopy = (destination) => readFileSync(join(destination, 'chrome/scripts/installManifest.mjs'), 'utf8');
  const consistent = (destination) => {
    assert.equal(readFileSync(join(destination, '.lcu-browser-plugin'), 'utf8').trim(), browser._plugin_digest(source));
    assert.equal(privateCopy(destination), readFileSync(installer, 'utf8'));
    assert.equal(existsSync(join(destination, '.chrome-previous')), false);
    assert.deepEqual(readdirSync(destination).filter((n) => n.startsWith('.lcu-browser-') && !['.lcu-browser-host', '.lcu-browser-plugin'].includes(n)), []);
  };

  it('stamp symlink is replaced not followed', () => {
    const destination = browser.install(root);
    const victim = join(home, 'victim');
    writeFileSync(victim, 'precious');
    const stamp = join(destination, '.lcu-browser-plugin');
    unlinkSync(stamp);
    symlinkSync(victim, stamp);
    writeFileSync(installer, 'version two');
    browser.install(root);
    assert.equal(readFileSync(victim, 'utf8'), 'precious');
    assert.equal(lstatSync(stamp).isSymbolicLink(), false);
    consistent(destination);
  });

  it('stamp symlink with a current copy is also repaired', () => {
    const destination = browser.install(root);
    const victim = join(home, 'victim');
    writeFileSync(victim, 'precious');
    const stamp = join(destination, '.lcu-browser-plugin');
    unlinkSync(stamp);
    symlinkSync(victim, stamp);
    browser.install(root);
    assert.equal(readFileSync(victim, 'utf8'), 'precious');
    assert.equal(lstatSync(stamp).isSymbolicLink(), false);
    consistent(destination);
  });

  it('interrupted between the renames is recovered', () => {
    const destination = browser.install(root);
    renameSync(join(destination, 'chrome'), join(destination, '.chrome-previous')); // chrome missing, copy retired
    writeFileSync(installer, 'version two');
    assert.equal(browser.install(root), destination);
    consistent(destination);
  });

  it('missing copy without a retired one is rebuilt', () => {
    const destination = browser.install(root);
    rmSync(join(destination, 'chrome'), { recursive: true });
    browser.install(root);
    consistent(destination);
  });

  it('failed staging leaves the published copy and digest untouched', () => {
    const destination = browser.install(root);
    writeFileSync(installer, 'version two');
    class KeyboardInterrupt extends Error {}
    browser.hooks.copytree = () => { throw new KeyboardInterrupt(); };
    assert.throws(() => browser.install(root), KeyboardInterrupt);
    browser.hooks.copytree = saved.copytree;
    assert.equal(privateCopy(destination), 'version one');
    browser.install(root);
    consistent(destination);
  });

  it('interrupted before the digest is written converges', () => {
    const destination = browser.install(root);
    writeFileSync(installer, 'version two');
    class KeyboardInterrupt extends Error {}
    browser.hooks._write_stamp = () => { throw new KeyboardInterrupt(); };
    assert.throws(() => browser.install(root), KeyboardInterrupt);
    browser.hooks._write_stamp = saved._write_stamp;
    assert.equal(privateCopy(destination), 'version two');
    browser.install(root);
    consistent(destination);
  });

  it('concurrent refreshes publish one matching copy and digest', { skip: skipOnWindows('concurrent refreshes contend for the destination lock; the Windows lock is msvcrt LK_LOCK (a waiter gives up after ten seconds) and each acquisition starts a PowerShell holder, so N parallel waiters are not a defined outcome there') }, async () => {
    // Python used six threads; here six worker threads, each with its own lock descriptor (flock is per open file
    // description, so they exclude each other exactly like Python's threads did). Overlap is counted in shared memory.
    const destination = browser.install(root);
    writeFileSync(installer, 'version two');
    const shared = new Int32Array(new SharedArrayBuffer(8));
    const code = `
      import { workerData, parentPort } from 'node:worker_threads';
      const browser = await import(${JSON.stringify(pathToFileURL(join(ROOT, 'lcu/browser.mjs')).href)});
      const { root, home, resources, shared } = workerData;
      const counters = new Int32Array(shared);
      process.env.HOME = home;
      const env = { HOME: home, NODE_REPL_NODE_PATH: '/fake/node', CODEX_CLI_PATH: '/fake/codex', CUA_REPL_NODE_REPL_PATH: '/fake/repl' };
      const fs = await import('node:fs');
      const path = await import('node:path');
      Object.assign(browser.hooks, {
        system: () => 'Darwin', paths: () => [path.join(root, 'app'), resources, null, {}], environment: () => env,
        capture_run: () => {
          const support = path.join(home, 'Library/Application Support');
          const destinations = path.join(support, 'lcu/browser');
          const dir = fs.readdirSync(destinations).find((d) => fs.statSync(path.join(destinations, d)).isDirectory());
          const manifest = path.join(support, 'Google/Chrome/NativeMessagingHosts/com.openai.codexextension.json');
          fs.mkdirSync(path.dirname(manifest), { recursive: true });
          const staged = manifest + '.' + Math.random();
          fs.writeFileSync(staged, JSON.stringify({ path: path.join(destinations, dir, 'chrome/extension-host/macos/arm64/ChatGPT for Chrome') }));
          fs.renameSync(staged, manifest);
          return { returncode: 0, stdout: '', stderr: '' };
        },
      });
      const real = browser.hooks._refresh_plugin;
      browser.hooks._refresh_plugin = (s, d) => {
        const now = Atomics.add(counters, 0, 1) + 1;
        Atomics.store(counters, 1, Math.max(Atomics.load(counters, 1), now));
        try { real(s, d); } finally { Atomics.sub(counters, 0, 1); }
      };
      try { browser.install(root); parentPort.postMessage('ok'); } catch (error) { parentPort.postMessage(String(error.stack)); }`;
    const results = await Promise.all(Array.from({ length: 6 }, () => new Promise((resolveWorker, reject) => {
      const worker = new Worker(code, { eval: true, workerData: { root, home, resources: join(root, 'app/Contents/Resources'), shared: shared.buffer } });
      worker.once('message', resolveWorker);
      worker.once('error', reject);
    })));
    assert.deepEqual(results, Array(6).fill('ok'));
    assert.equal(shared[1], 1);
    consistent(destination);
  });
});

describe('BrowserStatusTests', () => {
  let root; let hostDir; let relay; let manifest; let extension; let resources;

  beforeEach(() => {
    root = scratch();
    resources = join(root, 'app/Contents/Resources');
    const scripts = join(resources, 'plugins/openai-bundled/plugins/chrome/scripts');
    mkdirSync(scripts, { recursive: true });
    writeFileSync(join(scripts, 'extension-ids.json'), JSON.stringify({ browserDiagnostics: [{
      browserFamily: 'chrome', shortDisplayName: 'Chrome',
      extensionManagementUrl: 'chrome://extensions', storeUrl: 'https://official.example/extension' }] }));
    mkdirSync(join(root, 'app/Contents/MacOS'), { recursive: true });
    hostDir = join(root, 'private-host');
    mkdirSync(hostDir);
    writeFileSync(join(hostDir, '.lcu-browser-host'), `${realpathSync(join(root, 'app'))}\n`);
    writeFileSync(join(hostDir, '.lcu-browser-plugin'), `${browser._plugin_digest(join(resources, 'plugins/openai-bundled/plugins/chrome'))}\n`);
    releaseRelay(root);
    patch({ system: () => 'Darwin', stable_lcu: () => '/fixture prefix/current/bin/lcu' });
    relay = browser._publish_relay(root, hostDir, 'Darwin');
    const host = join(hostDir, 'chrome/extension-host/macos/arm64/ChatGPT for Chrome');
    mkdirSync(dirname(host), { recursive: true });
    writeFileSync(host, 'fixture host');
    chmodSync(host, 0o700);
    manifest = join(root, 'manifest.json');
    writeFileSync(manifest, JSON.stringify({ path: relay }));
    extension = { enabled: true, installed: true, selectedProfileDirectory: 'Default' };
    patch({
      paths: () => [null, resources, null, {}], environment: () => ({ NODE_REPL_NODE_PATH: '/original/node' }),
      system: () => 'Darwin', machine: () => 'arm64',
    });
  });
  afterEach(restore);

  const goodManifest = () => completed(0, JSON.stringify({ correct: true, manifestPath: manifest }));
  const runStatusWith = (results) => {
    const queue = [...results];
    browser.hooks.capture_run = () => queue.shift();
    return capture(() => browser.status(root));
  };
  const runStatus = () => runStatusWith([completed(0, JSON.stringify(extension)), goodManifest()]);

  it('large diagnostic output survives node exit (capture.run)', async () => {
    const { run } = await import('../../lcu/capture.mjs');
    const script = join(root, 'big.js');
    writeFileSync(script, "console.log(JSON.stringify({installed:true,enabled:true,pad:'x'.repeat(200000)}));process.exit(0);");
    const result = run([process.execPath, script], { timeout: 20 });
    assert.ok(result.stdout.length > 65536);
    assert.equal(JSON.parse(result.stdout).enabled, true);
  });

  it('unparseable diagnostic output is reported honestly', () => {
    const [, out] = runStatusWith([completed(0, 'not json'), goodManifest()]);
    assert.ok(out.includes('could not be parsed (8 bytes)'));
    assert.ok(!out.includes('returned no result'));
  });

  it('non-object diagnostic output is a problem', () => {
    const [, out] = runStatusWith([completed(0, '[1]'), goodManifest()]);
    assert.ok(out.includes('could not be parsed'));
  });

  it('diagnostic stderr is shown when unparseable', () => {
    const [, out] = runStatusWith([completed(1, '', 'boom happened'), goodManifest()]);
    assert.ok(out.includes('boom happened'));
  });

  it('valid setup does not claim live connection or write files', { skip: skipOnWindows('status/refresh of the POSIX /bin/sh relay launcher of Linux and macOS (lcu-native-host, mode bits, sh); the Windows relay is the .cmd wrapper covered by the windows cases') }, () => {
    const snapshot = () => {
      const files = new Map();
      const walk = (dir) => {
        for (const entry of readdirSync(dir, { withFileTypes: true })) {
          const path = join(dir, entry.name);
          if (entry.isDirectory()) walk(path);
          else if (entry.isFile()) files.set(path, readFileSync(path).toString('hex'));
        }
      };
      walk(root);
      return files;
    };
    const before = snapshot();
    const [ok, out] = runStatus();
    assert.equal(ok, true, out);
    assert.ok(out.includes('Live browser connection: not checked'));
    assert.deepEqual(snapshot(), before);
    assert.equal(out, 'Chrome extension: enabled in Default.\nChrome connector: configured for this LCU installation.\n'
      + 'Live browser connection: not checked. After setup, restart Chrome, or turn the ChatGPT extension off and on at '
      + "chrome://extensions, so an already-connected extension reconnects through LCU's relay. "
      + 'Then ask your agent to use LCU to list Chrome tabs.\n');
    assert.ok(out.includes('turn the ChatGPT extension off and on at chrome://extensions'));
  });

  it('enabled extension with original host is not lcu ready', () => {
    writeFileSync(manifest, JSON.stringify({ path: '/original/ChatGPT for Chrome' }));
    const [ok, out] = runStatus();
    assert.equal(ok, false);
    assert.ok(out.includes('lcu browser install'));
  });

  // ---- upstream 0.9.6 (#18): where the manifest points and how to reconnect ----
  it('manifest pointing at original host says where and how to fix', { skip: skipOnWindows('status/refresh of the POSIX /bin/sh relay launcher of Linux and macOS (lcu-native-host, mode bits, sh); the Windows relay is the .cmd wrapper covered by the windows cases') }, () => {
    writeFileSync(manifest, JSON.stringify({ path: '/original/ChatGPT for Chrome' }));
    const [ok, text] = runStatus();
    assert.equal(ok, false);
    assert.ok(text.includes("points to /original/ChatGPT for Chrome, not this LCU installation's relay"), text);
    assert.ok(text.includes('Run `lcu browser install`, then restart Chrome, or turn the ChatGPT extension off and on '
      + 'at chrome://extensions'), text);
  });

  it('relay of another LCU installation is reported with its path', () => {
    writeFileSync(join(hostDir, '.lcu-browser-host'), '/other/installation/app\n');
    const [ok, text] = runStatus();
    assert.equal(ok, false);
    assert.ok(text.includes(`points to ${relay}, not this LCU installation's relay`), text);
    assert.ok(text.includes('Run `lcu browser install`, then restart Chrome'), text);
  });

  it('install command prints reconnect step', async () => {
    browser.hooks.install = () => '/fixture/host';
    const [, out] = await (async () => {
      let text = '';
      const real = io.stdout;
      io.stdout = (t) => { text += t; };
      try { await browser.main(root, ['install']); } finally { io.stdout = real; }
      return [null, text];
    })();
    assert.ok(out.includes('turn the extension off and on'), out);
    assert.equal(out, 'LCU browser native host configured: /fixture/host\n'
      + 'Install or enable the official ChatGPT browser extension in the browser you want to use.\n'
      + 'The extension and browser must run under this same desktop account. See docs/INSTALLATION.md.\n'
      + "If the extension was already connected, restart the browser or turn the extension off and on in its extensions page so it reconnects through LCU's relay.\n"
      + 'Check extension and connector setup with: lcu browser status\n');
  });

  it('outdated LCU relay is not reported as foreign host', { skip: skipOnWindows('status/refresh of the POSIX /bin/sh relay launcher of Linux and macOS (lcu-native-host, mode bits, sh); the Windows relay is the .cmd wrapper covered by the windows cases') }, () => {
    writeFileSync(relay, 'old relay');
    const [ok, text] = runStatus();
    assert.equal(ok, false);
    assert.ok(text.includes('missing or outdated'));
    assert.ok(!text.includes("not this LCU installation's relay"));
  });

  it('a damaged launcher or one for another directory requires refresh (Node form of the wrapper cases)', { skip: skipOnWindows('status/refresh of the POSIX /bin/sh relay launcher of Linux and macOS (lcu-native-host, mode bits, sh); the Windows relay is the .cmd wrapper covered by the windows cases') }, () => {
    const good = readFileSync(relay, 'utf8');
    for (const damaged of [good.replace('exit 1', 'exit 0'), `${good}# extra\n`, '#!/bin/sh\nexit 0\n',
      browser._relay_launcher('/fixture prefix/current/bin/lcu', join(hostDir, 'elsewhere'), 'Darwin').toString()]) {
      assert.notEqual(damaged, good);
      writeFileSync(relay, damaged);
      const [ok, text] = runStatus();
      assert.equal(ok, false);
      assert.ok(text.includes('missing or outdated'), text);
    }
  });

  it('a missing relay implementation in the release requires refresh, not a foreign-host diagnosis (upstream: single file install without the script)', { skip: skipOnWindows('status/refresh of the POSIX /bin/sh relay launcher of Linux and macOS (lcu-native-host, mode bits, sh); the Windows relay is the .cmd wrapper covered by the windows cases') }, () => {
    for (const relative of ['lcu/native_host.mjs', 'lcu/compat/pyjson.mjs']) {
      const saved = readFileSync(join(root, relative));
      unlinkSync(join(root, relative));
      const [ok, text] = runStatus();
      assert.equal(ok, false, relative);
      assert.ok(text.includes('missing or outdated'), text);
      assert.ok(!text.includes("not this LCU installation's relay"), text);
      writeFileSync(join(root, relative), saved);
    }
    assert.equal(runStatus()[0], true);
  });

  it('a relay implementation stamp of another release requires refresh (upstream: outdated copied script)', { skip: skipOnWindows('status/refresh of the POSIX /bin/sh relay launcher of Linux and macOS (lcu-native-host, mode bits, sh); the Windows relay is the .cmd wrapper covered by the windows cases') }, () => {
    writeFileSync(join(hostDir, '.lcu-relay-implementation'), `${'0'.repeat(64)}\n`);
    const [ok, text] = runStatus();
    assert.equal(ok, false);
    assert.ok(text.includes('missing or outdated'));
    unlinkSync(join(hostDir, '.lcu-relay-implementation'));
    assert.equal(runStatus()[0], false);
  });

  it('the recorded implementation is the import closure of lcu/native_host.mjs (and loads on its own)', async () => {
    const closure = browser._relay_implementation(ROOT);
    assert.ok(closure.includes('lcu/native_host.mjs') && closure.includes('lcu/compat/pyjson.mjs') && closure.includes('lcu/compat/pyerr.mjs'), closure.join());
    const copy = scratch();
    for (const relative of closure) {
      mkdirSync(dirname(join(copy, relative)), { recursive: true });
      writeFileSync(join(copy, relative), readFileSync(join(ROOT, relative)));
    }
    const loaded = await import(pathToFileURL(join(copy, 'lcu/native_host.mjs')).href); // nothing outside the closure
    assert.equal(typeof loaded.run, 'function');
  });

  it('missing wrapper requires refresh', { skip: skipOnWindows('status/refresh of the POSIX /bin/sh relay launcher of Linux and macOS (lcu-native-host, mode bits, sh); the Windows relay is the .cmd wrapper covered by the windows cases') }, () => {
    unlinkSync(relay);
    const [ok, text] = runStatus();
    assert.equal(ok, false);
    assert.ok(text.includes('missing or outdated'));
  });

  it('outdated relay requires refresh', () => {
    writeFileSync(relay, 'old relay');
    assert.equal(runStatus()[0], false);
  });

  it('a launcher for another prefix or a Python-era relay requires refresh', { skip: skipOnWindows('status/refresh of the POSIX /bin/sh relay launcher of Linux and macOS (lcu-native-host, mode bits, sh); the Windows relay is the .cmd wrapper covered by the windows cases') }, () => {
    writeFileSync(relay, browser._relay_launcher('/other/current/bin/lcu', hostDir, 'Darwin'));
    assert.equal(runStatus()[0], false);
    browser._publish_relay(root, hostDir, 'Darwin');
    assert.equal(runStatus()[0], true);
    writeFileSync(relay, readFileSync(join(ORACLE_ROOT, 'lcu/native_host.py')));
    assert.equal(runStatus()[0], false);
  });

  it('missing extension has store link and profile', () => {
    extension.enabled = false;
    extension.installed = false;
    const [ok, out] = runStatus();
    assert.equal(ok, false);
    assert.ok(out.includes('not found in Default'));
    assert.ok(out.includes('https://official.example/extension'));
  });

  it('disabled extension is not reinstalled', () => {
    extension.enabled = false;
    const [ok, out] = runStatus();
    assert.equal(ok, false);
    assert.ok(out.includes('Enable it at chrome://extensions'));
  });

  it('main exits 1 when not ready and prints the help/usage errors like Python', async () => {
    extension.enabled = false;
    const queue = [completed(0, JSON.stringify(extension)), goodManifest()];
    browser.hooks.capture_run = () => queue.shift();
    let out = '';
    const real = io.stdout;
    io.stdout = (text) => { out += text; };
    try {
      await assert.rejects(browser.main(root, ['status']), (e) => e instanceof PySystemExit && e.status === 1);
    } finally { io.stdout = real; }
    assert.ok(out.includes('disabled in Default'));
  });

  it('argparse text matches CPython 3.12', { skip: !PYTHON }, async () => {
    const cases = [['--help'], ['install', '--help'], ['status', '--help'], [], ['serve'], ['protocol', 'x'], ['status', '--browser', 'safari'], ['bogus']];
    const script = `
import contextlib, io, sys, json
sys.argv[0] = '/x/bin/lcu'
sys.path.insert(0, ${JSON.stringify(ORACLE_ROOT)})
from lcu import browser
out = []
for argv in json.loads(sys.stdin.read()):
    o, e = io.StringIO(), io.StringIO()
    code = None
    with contextlib.redirect_stdout(o), contextlib.redirect_stderr(e):
        try:
            browser.main('/nonexistent', argv)
        except SystemExit as exit_:
            code = exit_.code
    out.append([code, o.getvalue(), e.getvalue()])
print(json.dumps(out))`;
    const python = spawnSync(PYTHON, ['-c', script], { input: JSON.stringify(cases), encoding: 'utf8', env: { ...process.env, COLUMNS: '80' } });
    assert.equal(python.status, 0, python.stderr);
    const got = [];
    for (const argv of cases) {
      let o = ''; let e = '';
      const real = { stdout: io.stdout, stderr: io.stderr, exit: io.exit };
      Object.assign(io, { stdout: (t) => { o += t; }, stderr: (t) => { e += t; }, exit: (s) => { throw new PySystemExit(s); } });
      let code = null;
      try { await browser.main('/nonexistent', argv); } catch (error) {
        if (!(error instanceof PySystemExit)) throw error;
        code = error.status;
      } finally { Object.assign(io, real); }
      got.push([code, o, e]);
    }
    assert.deepEqual(got, JSON.parse(python.stdout));
  });
});

describe('plugin digest', () => {
  it('equals the Python digest byte for byte (ordering, modes, links, nested and odd names)', { skip: !PYTHON }, () => {
    const plugin = join(scratch(), 'chrome');
    mkdirSync(join(plugin, 'a/b'), { recursive: true });
    mkdirSync(join(plugin, 'a-c'), { recursive: true });
    mkdirSync(join(plugin, '.hidden'), { recursive: true });
    writeFileSync(join(plugin, 'a/b/x'), 'x');
    writeFileSync(join(plugin, 'a-c/y'), 'y');
    writeFileSync(join(plugin, '.hidden/z'), 'z');
    writeFileSync(join(plugin, 'é\u{1F600}'), 'astral');
    writeFileSync(join(plugin, '\uff10'), 'bmp-high');
    writeFileSync(join(plugin, 'run'), 'exec');
    chmodSync(join(plugin, 'run'), 0o751);
    symlinkSync('a/b', join(plugin, 'linkdir'));
    symlinkSync('missing', join(plugin, 'dangling'));
    const python = spawnSync(PYTHON, ['-c', `import sys; sys.path.insert(0, ${JSON.stringify(ORACLE_ROOT)}); from lcu.browser import _plugin_digest; print(_plugin_digest(sys.argv[1]))`, plugin], { encoding: 'utf8' });
    assert.equal(python.status, 0, python.stderr);
    assert.equal(browser._plugin_digest(plugin), python.stdout.trim());
  });
});

describe('relay launcher', () => {
  afterEach(restore);

  it('names the stable installation command, never a Node binary', () => {
    const base = scratch();
    const release = join(base, 'prefix/releases/0.9.5-aaaaaaaaaaaa');
    mkdirSync(release, { recursive: true });
    assert.equal(browser._stable_lcu(release, 'Darwin'), join(base, 'prefix/current/bin/lcu'));
    assert.equal(browser._stable_lcu(release, 'Linux'), join(base, 'prefix/current/bin/lcu'));
    assert.equal(browser._stable_lcu(release, 'Windows'), join(base, 'prefix/lcu.cmd'));
    assert.equal(browser._stable_lcu(join(base, 'checkout'), 'Linux'), join(base, 'checkout/bin/lcu')); // development
    const text = browser._relay_launcher('/p q/current/bin/lcu', "/h o'st", 'Linux').toString();
    assert.equal(text, POSIX_LAUNCHER('/p q/current/bin/lcu', "/h o'st"));
    assert.ok(!/node/.test(text.replace('native-host', '')), text);
    if (process.platform !== 'win32') assert.equal(spawnSync('/bin/sh', ['-n', '-c', text]).status, 0); // no sh on Windows
    assert.equal(browser._relay_launcher('C:\\P\\lcu.cmd', 'C:\\h', 'Windows').toString(), WINDOWS_CMD('C:\\P\\lcu.cmd'));
  });

  it('a removed prefix fails with a message on stderr only (stdout is Chrome\'s framed channel)', { skip: skipOnWindows('status/refresh of the POSIX /bin/sh relay launcher of Linux and macOS (lcu-native-host, mode bits, sh); the Windows relay is the .cmd wrapper covered by the windows cases') }, () => {
    const dir = scratch();
    writeFileSync(join(dir, 'lcu-native-host'), browser._relay_launcher(join(dir, 'gone/current/bin/lcu'), dir, 'Linux'));
    chmodSync(join(dir, 'lcu-native-host'), 0o700);
    const result = spawnSync(join(dir, 'lcu-native-host'), ['chrome-extension://x/'], { input: '' });
    assert.equal(result.status, 1);
    assert.equal(result.stdout.length, 0);
    assert.equal(result.stderr.toString(), `LCU Chrome native-host relay: ${join(dir, 'gone/current/bin/lcu')} is missing; reinstall LCU, then run \`lcu browser install\`.\n`);
  });

  it('`lcu browser __native-host` without a directory is refused on stderr', async () => {
    let err = '';
    const real = io.stderr;
    io.stderr = (text) => { err += text; };
    try {
      await assert.rejects(browser.main(scratch(), ['__native-host']), (e) => e instanceof PySystemExit && e.status === 2);
    } finally { io.stderr = real; }
    assert.equal(err, 'LCU Chrome native-host relay: missing host directory.\n');
  });

  // End to end through an installed-layout fixture prefix: launcher -> <prefix>/current/bin/lcu (the real
  // bin/lcu shim with its pre-Node gate and quarantine) -> lcu/entry.mjs -> runtime -> browser.main ->
  // native_host.run -> a fake original host (a shell script that records its environment and echoes stdin).
  const APP_NODE = '/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node';
  // The shim's gate requires the physical Node to be <selected app>/.../cua_node/bin/node and the release's `app`
  // link to name that app (tests/node/entry.test.mjs does the same). Linux: a copy of this Node in a fake app tree.
  const NODE_IN_APP = process.platform === 'darwin' ? '/Contents/Resources/cua_node/bin/node' : '/resources/cua_node/bin/node';
  let linuxApp = null;
  const trustedNode = () => {
    if (process.platform === 'darwin') return existsSync(APP_NODE) ? APP_NODE : null;
    if (linuxApp === null) {
      linuxApp = join(scratch(), 'chatgpt');
      mkdirSync(join(linuxApp, 'resources/cua_node/bin'), { recursive: true });
      writeFileSync(join(linuxApp, NODE_IN_APP), readFileSync(process.execPath));
      chmodSync(join(linuxApp, NODE_IN_APP), 0o755);
    }
    return join(linuxApp, NODE_IN_APP);
  };
  const gateNode = process.platform === 'win32' ? null : trustedNode();
  const shimmed = { skip: (process.platform === 'win32' || gateNode === null) && 'needs a gate-passing Node (macOS: the official app\'s cua_node)' };

  function installedPrefix(base, node = gateNode) {
    const prefix = join(base, 'prefix');
    const release = join(prefix, 'releases/0.9.5-aaaaaaaaaaaa');
    mkdirSync(join(release, 'bin'), { recursive: true });
    mkdirSync(join(release, 'agent-tools/node/bin'), { recursive: true });
    spawnSync('cp', ['-R', join(ROOT, 'lcu'), join(release, 'lcu')]);
    writeFileSync(join(release, 'bin/lcu'), readFileSync(join(ROOT, 'bin/lcu')));
    chmodSync(join(release, 'bin/lcu'), 0o755);
    symlinkSync(node, join(release, 'agent-tools/node/bin/node'));
    symlinkSync(node.endsWith(NODE_IN_APP) ? node.slice(0, -NODE_IN_APP.length) : dirname(node), join(release, 'app'));
    symlinkSync('releases/0.9.5-aaaaaaaaaaaa', join(prefix, 'current'));
    return { prefix, release };
  }

  function hostDirectory(base, release) {
    const dir = join(base, 'host');
    const segment = process.platform === 'darwin' ? 'macos' : 'linux';
    const arch = { arm64: 'arm64', aarch64: 'arm64', x86_64: 'x64' }[(spawnSync('uname', ['-m'], { encoding: 'utf8' }).stdout ?? '').trim()];
    const host = join(dir, 'chrome/extension-host', segment, arch, segment === 'macos' ? 'ChatGPT for Chrome' : 'extension-host');
    mkdirSync(dirname(host), { recursive: true });
    writeFileSync(host, `#!/bin/sh\nprintf '%s|%s' "\${NODE_OPTIONS-unset}" "\${__LCU_Q-unset}" > ${shq(join(dir, 'host-env'))}\nexec cat\n`);
    chmodSync(host, 0o755);
    patch({ system: () => (process.platform === 'darwin' ? 'Darwin' : 'Linux') });
    const relay = browser._publish_relay(release, dir, browser.hooks.system());
    return { dir, relay };
  }

  const message = Buffer.from('{"result":{"type":"extension","agentRequestHeaderEnabled":false}}');
  const framed = (body) => {
    const prefix = Buffer.alloc(4);
    prefix.writeUInt32LE(body.length);
    return Buffer.concat([prefix, body]);
  };

  it('Chrome-inherited NODE_OPTIONS cannot run code in the relay; the original host still receives it', shimmed, () => {
    const base = scratch();
    const { release } = installedPrefix(base);
    const { dir, relay } = hostDirectory(base, release);
    const preload = join(base, 'preload.cjs');
    writeFileSync(preload, "process.stdout.write('PRELOAD\\n'); process.exit(41);");
    const result = spawnSync(relay, ['chrome-extension://x/'], {
      input: framed(message), timeout: 60000,
      env: { PATH: '/usr/bin:/bin', HOME: base, NODE_OPTIONS: `--require=${preload}` },
    });
    assert.equal(result.status, 0, String(result.stderr));
    assert.deepEqual(result.stdout, framed(Buffer.from('{"result":{"type":"extension","agentRequestHeaderEnabled":true}}')));
    assert.equal(readFileSync(join(dir, 'host-env'), 'utf8'), `--require=${preload}|unset`);
  });

  it('an invalid NODE_OPTIONS from Chrome does not stop the relay', shimmed, () => {
    const base = scratch();
    const { release } = installedPrefix(base);
    const { relay } = hostDirectory(base, release);
    const result = spawnSync(relay, [], {
      input: framed(Buffer.from('{}')), timeout: 60000, env: { PATH: '/usr/bin:/bin', HOME: base, NODE_OPTIONS: '--no-such-option' },
    });
    assert.equal(result.status, 0, String(result.stderr));
    assert.deepEqual(result.stdout, framed(Buffer.from('{}')));
  });

  it('the pre-Node gate refuses an untrusted Node before it runs, with nothing on stdout', { skip: process.platform === 'win32' }, () => {
    const base = scratch();
    const fake = join(base, 'open/node');
    mkdirSync(dirname(fake), { recursive: true });
    writeFileSync(fake, '#!/bin/sh\necho UNVERIFIED\nexit 42\n');
    chmodSync(fake, 0o755);
    chmodSync(dirname(fake), 0o777); // group/other-writable ancestor (Linux gate); unsigned binary (macOS gate)
    const { release } = installedPrefix(base, fake);
    const { relay } = hostDirectory(base, release);
    const result = spawnSync(relay, [], { input: framed(message), timeout: 60000, env: { PATH: '/usr/bin:/bin', HOME: base } });
    assert.equal(result.status, 1);
    assert.equal(result.stdout.length, 0);
    assert.match(result.stderr.toString(), /^LCU: Cannot run the ChatGPT app's bundled Node \(/);
  });

  it('pruning the release that wrote the launcher does not break it (it follows current)', shimmed, () => {
    const base = scratch();
    const { prefix, release } = installedPrefix(base);
    const { relay } = hostDirectory(base, release);
    const next = join(prefix, 'releases/0.9.6-bbbbbbbbbbbb');
    renameSync(release, next); // the old release disappears, `current` now names the new one
    unlinkSync(join(prefix, 'current'));
    symlinkSync('releases/0.9.6-bbbbbbbbbbbb', join(prefix, 'current'));
    const result = spawnSync(relay, [], { input: framed(Buffer.from('{}')), timeout: 60000, env: { PATH: '/usr/bin:/bin', HOME: base } });
    assert.equal(result.status, 0, String(result.stderr));
    assert.deepEqual(result.stdout, framed(Buffer.from('{}')));
  });
});

describe('relay migration (BRIEF addendum G)', () => {
  afterEach(restore);
  const STABLE = '/opt/lcu/current/bin/lcu';

  function pythonEraFixture(system = 'Darwin') {
    const base = scratch();
    const root = join(base, 'release');
    const home = join(base, 'home');
    mkdirSync(join(root, 'app'), { recursive: true });
    releaseRelay(root);
    const support = system === 'Darwin' ? join(home, 'Library/Application Support') : join(home, '.local/share');
    const destination = join(support, 'lcu/browser', '0123456789abcdef');
    mkdirSync(join(destination, 'chrome'), { recursive: true });
    writeFileSync(join(destination, '.lcu-browser-host'), `${realpathSync(join(root, 'app'))}\n`);
    // What an earlier (Python) release wrote: a copy of lcu/native_host.py as the executable relay.
    writeFileSync(join(destination, 'lcu-native-host'), readFileSync(join(ORACLE_ROOT, 'lcu/native_host.py')));
    chmodSync(join(destination, 'lcu-native-host'), 0o700);
    const manifestDir = system === 'Darwin'
      ? join(home, 'Library/Application Support/Google/Chrome/NativeMessagingHosts')
      : join(home, '.config/google-chrome/NativeMessagingHosts');
    mkdirSync(manifestDir, { recursive: true });
    const manifest = join(manifestDir, 'com.openai.codexextension.json');
    const manifestText = `{\n  "name": "com.openai.codexextension",\n  "path": ${JSON.stringify(join(destination, 'lcu-native-host'))}\n}\n`;
    writeFileSync(manifest, manifestText);
    return { root, home, destination, manifest, manifestText };
  }

  const clearXdg = () => {
    delete process.env.XDG_DATA_HOME;
    delete process.env.XDG_CONFIG_HOME;
    delete process.env.CHROME_CONFIG_HOME;
  };

  for (const system of ['Darwin', 'Linux']) {
    it(`refreshes an owner-marked Python-era relay to the stable launcher (${system})`, { skip: skipOnWindows('status/refresh of the POSIX /bin/sh relay launcher of Linux and macOS (lcu-native-host, mode bits, sh); the Windows relay is the .cmd wrapper covered by the windows cases') }, () => {
      const { root, home, destination, manifest, manifestText } = pythonEraFixture(system);
      patch({ system: () => system, stable_lcu: () => STABLE });
      clearXdg();
      assert.deepEqual(browser.migrate_relays(root, home), [destination]);
      assert.equal(readFileSync(join(destination, 'lcu-native-host'), 'utf8'), POSIX_LAUNCHER(STABLE, destination));
      assert.equal(statSync(join(destination, 'lcu-native-host')).mode & 0o777, 0o700);
      assert.equal(readFileSync(manifest, 'utf8'), manifestText); // the relay path Chrome knows does not change
      assert.deepEqual(browser.migrate_relays(root, home), []); // idempotent
    });
  }

  it('leaves foreign, unmarked or other-installation directories alone and creates nothing new', () => {
    const { root, home, destination } = pythonEraFixture();
    patch({ system: () => 'Darwin', stable_lcu: () => STABLE });
    writeFileSync(join(destination, '.lcu-browser-host'), '/some/other/app\n');
    const before = readFileSync(join(destination, 'lcu-native-host'));
    assert.deepEqual(browser.migrate_relays(root, home), []);
    assert.deepEqual(readFileSync(join(destination, 'lcu-native-host')), before);
    unlinkSync(join(destination, '.lcu-browser-host'));
    assert.deepEqual(browser.migrate_relays(root, home), []);
    const empty = scratch();
    assert.deepEqual(browser.migrate_relays(root, empty), []);
    assert.deepEqual(readdirSync(empty), []);
  });

  it('a custom --directory relay found through its manifest is refreshed too', { skip: skipOnWindows('status/refresh of the POSIX /bin/sh relay launcher of Linux and macOS (lcu-native-host, mode bits, sh); the Windows relay is the .cmd wrapper covered by the windows cases') }, () => {
    const { root, home, manifest } = pythonEraFixture();
    const custom = join(home, 'custom-host');
    mkdirSync(custom);
    writeFileSync(join(custom, '.lcu-browser-host'), `${realpathSync(join(root, 'app'))}\n`);
    writeFileSync(join(custom, 'lcu-native-host'), '#!/usr/bin/env python3\n');
    writeFileSync(manifest, JSON.stringify({ path: join(custom, 'lcu-native-host') }));
    patch({ system: () => 'Darwin', stable_lcu: () => STABLE });
    const refreshed = browser.migrate_relays(root, home);
    assert.ok(refreshed.includes(custom), refreshed.join(','));
    assert.equal(readFileSync(join(custom, 'lcu-native-host'), 'utf8'), POSIX_LAUNCHER(STABLE, custom));
  });

  it('windows: a relay of an older app generation of this prefix is rewritten; then prune cannot strand it', () => {
    const base = scratch();
    const prefix = join(base, 'prefix');
    const root = join(prefix, 'releases/0.9.6-bbbbbbbbbbbb');
    releaseRelay(root);
    const home = join(base, 'account');
    const local = join(home, 'AppData/Local');
    const oldApp = join(prefix, 'apps', 'a'.repeat(64), 'app');
    const newApp = join(prefix, 'apps', 'b'.repeat(64), 'app');
    const destination = join(local, 'lcu/browser/0123456789abcdef');
    mkdirSync(destination, { recursive: true });
    writeFileSync(join(destination, '.lcu-browser-host'), `${oldApp}\n`);
    writeFileSync(join(destination, 'lcu-native-host.py'), readFileSync(join(ORACLE_ROOT, 'lcu/native_host.py')));
    writeFileSync(join(destination, 'lcu-native-host.cmd'), '@echo off\r\n"C:\\Python313\\python.exe" -B -u "%~dp0lcu-native-host.py" %*\r\nexit /b %ERRORLEVEL%\r\n');
    patch({ system: () => 'Windows', paths: () => [newApp, null, null, {}] }, { LOCALAPPDATA: local });
    assert.deepEqual(browser.migrate_relays(root, home), [destination]);
    // The wrapper names only <prefix>\lcu.cmd, which resolves current.json (and its app generation) at launch.
    assert.equal(readFileSync(join(destination, 'lcu-native-host.cmd'), 'utf8'), WINDOWS_CMD(join(prefix, 'lcu.cmd')));
    assert.ok(!readFileSync(join(destination, 'lcu-native-host.cmd'), 'utf8').includes('apps'));
    assert.equal(existsSync(join(destination, 'lcu-native-host.py')), false);
  });

  it('re-validates the destination under the lock: a directory swapped for a symlink while waiting is left alone (R5)', () => {
    const { root, home, destination } = pythonEraFixture();
    patch({ system: () => 'Darwin', stable_lcu: () => STABLE });
    // A separate directory that would pass every file check (matching marker and a relay).
    const elsewhere = join(scratch(), 'elsewhere');
    mkdirSync(elsewhere);
    writeFileSync(join(elsewhere, '.lcu-browser-host'), readFileSync(join(destination, '.lcu-browser-host')));
    writeFileSync(join(elsewhere, 'lcu-native-host'), 'python relay');
    chmodSync(join(elsewhere, 'lcu-native-host'), 0o700);
    const listing = () => readdirSync(elsewhere).sort().map((n) => [n, readFileSync(join(elsewhere, n)).toString('hex')]);
    const before = listing();
    const parentBefore = readdirSync(dirname(elsewhere)).sort();
    const realAcquire = browser.hooks.acquire;
    browser.hooks.acquire = (path) => {
      rmSync(destination, { recursive: true });
      symlinkSync(elsewhere, destination); // replaced during the lock wait
      return realAcquire(path);
    };
    assert.deepEqual(browser.migrate_relays(root, home), []);
    assert.deepEqual(listing(), before);
    assert.deepEqual(readdirSync(dirname(elsewhere)).sort(), parentBefore);
    assert.equal(lstatSync(destination).isSymbolicLink(), true);
  });

  it('a lock lost before or during the work stops every later change (R4, Windows holder death seam)', () => {
    const { root, home, destination } = pythonEraFixture();
    patch({ system: () => 'Darwin', stable_lcu: () => STABLE });
    const before = readFileSync(join(destination, 'lcu-native-host'));
    const deadLock = (path) => ({ path, held: false, lost: true, release() {} });
    browser.hooks.acquire = deadLock;
    assert.throws(() => browser.migrate_relays(root, home), (e) => e.name === 'ValueError' && /was lost/.test(e.message));
    assert.deepEqual(readFileSync(join(destination, 'lcu-native-host')), before);
  });
});

describe('lock loss during install (R4)', () => {
  afterEach(restore);

  it('a holder that dies during a refresh stops before publishing the copy, the stamp, the relay or manifests', () => {
    const base = scratch();
    const root = join(base, 'release');
    const home = join(base, 'home');
    mkdirSync(home);
    const resources = join(root, 'app/Contents/Resources');
    const source = join(resources, 'plugins/openai-bundled/plugins/chrome');
    mkdirSync(join(source, 'scripts'), { recursive: true });
    writeFileSync(join(source, 'scripts/installManifest.mjs'), 'version one');
    releaseRelay(root);
    const support = join(home, 'Library/Application Support');
    const manifest = join(support, 'Google/Chrome/NativeMessagingHosts/com.openai.codexextension.json');
    const env = { HOME: home, NODE_REPL_NODE_PATH: '/fake/node' };
    const original = () => {
      const destinations = join(support, 'lcu/browser');
      const privateDir = join(destinations, readdirSync(destinations).find((d) => statSync(join(destinations, d)).isDirectory()), 'chrome');
      mkdirSync(dirname(manifest), { recursive: true });
      writeFileSync(manifest, JSON.stringify({ path: join(privateDir, 'extension-host/macos/arm64/ChatGPT for Chrome') }));
      return completed(0);
    };
    patch({ system: () => 'Darwin', paths: () => [join(root, 'app'), resources, null, {}], environment: () => env,
      capture_run: original, stable_lcu: () => STABLE_FOR_INSTALL }, { HOME: home });
    const destination = browser.install(root);
    const snapshot = () => readdirSync(destination).sort().map((n) => [n, statSync(join(destination, n)).isFile() ? readFileSync(join(destination, n)).toString('hex') : 'dir']);
    writeFileSync(join(source, 'scripts/installManifest.mjs'), 'version two');
    const before = snapshot();
    let lost = false;
    browser.hooks.acquire = (path) => ({ path, get held() { return !lost; }, get lost() { return lost; }, release() {} });
    browser.hooks.copytree = (from, to) => { saved.copytree(from, to); lost = true; }; // the holder dies mid-refresh
    assert.throws(() => browser.install(root), (e) => /was lost/.test(e.message));
    assert.deepEqual(snapshot(), before);
    assert.equal(readFileSync(join(destination, 'chrome/scripts/installManifest.mjs'), 'utf8'), 'version one');
  });
});
const STABLE_FOR_INSTALL = '/opt/lcu/current/bin/lcu';

describe('Windows-shaped paths end to end (review round 2, R5)', () => {
  // The Windows flavour on this POSIX host: native `C:\...` paths are mapped onto a temporary directory, so
  // browser publication -> post-install migration -> prune run through PureWindowsPath joins, parents, names and
  // comparisons exactly as on Windows. Fixture only: no live Windows claim.
  let maintenance;
  let base;
  const toHost = (path) => (/^[A-Za-z]:[\\/]/.test(path) ? `${base}/${path.slice(3).replaceAll('\\', '/')}` : path);
  const fromHost = (path) => (path === base || path.startsWith(`${base}/`)
    ? `C:\\${path.slice(base.length + 1).replaceAll('/', '\\')}` : path);
  const native = { to: toHost, from: fromHost };

  beforeEach(async () => {
    maintenance = await import('../../lcu/maintenance.mjs');
    base = scratch();
    patch({ windows_paths: () => true, native: () => native, system: () => 'Windows' });
    Object.assign(maintenance.hooks, { windows_paths: () => true, native: () => native });
  });
  afterEach(() => {
    restore();
    Object.assign(maintenance.hooks, { windows_paths: () => process.platform === 'win32', native: () => ({ to: (p) => p, from: (p) => p }) });
  });

  const A = 'a'.repeat(64);
  const B = 'b'.repeat(64);
  const host = (path) => toHost(path);
  const write = (path, data) => { mkdirSync(dirname(host(path)), { recursive: true }); writeFileSync(host(path), data); };

  function windowsInstall() {
    const prefix = 'C:\\LCU';
    for (const digest of [A, B]) {
      const app = `${prefix}\\apps\\${digest}\\app`;
      write(`${app}\\resources\\plugins\\openai-bundled\\plugins\\chrome\\scripts\\installManifest.mjs`, 'fixture');
      write(`${app}\\resources\\plugins\\openai-bundled\\plugins\\chrome\\extension-host\\windows\\x64\\extension-host.exe`, 'host');
      write(`${app}\\resources\\cua_node\\bin\\node.exe`, 'node');
    }
    for (const [name, digest, stamp] of [['0.9.5-aaaaaaaaaaaa', A, 100], ['0.9.6-bbbbbbbbbbbb', B, 200]]) {
      const root = `${prefix}\\releases\\${name}`;
      write(`${root}\\installation.json`, JSON.stringify({ platform: 'windows', app: `${prefix}\\apps\\${digest}\\app` }));
      for (const relative of RELAY_CLOSURE) write(`${root}\\${relative.replaceAll('/', '\\')}`, readFileSync(join(ROOT, relative)));
      utimesSync(host(root), stamp, stamp);
    }
    write(`${prefix}\\.lcu-install`, '');
    return prefix;
  }

  function useRelease(prefix, name, digest) {
    write(`${prefix}\\current.json`, JSON.stringify({ release: name }));
    const app = `${prefix}\\apps\\${digest}\\app`;
    patch({ paths: () => [app, `${app}\\resources`, null, {}] });
    return `${prefix}\\releases\\${name}`;
  }

  it('publication, migration and prune select Windows paths (stable C:\\LCU\\lcu.cmd, generations, pins)', { skip: skipOnWindows('drives a fake C: drive mapped to a temp directory through flavour.native, a mechanism for non-Windows hosts; on Windows the same paths are real and the cases above run them') }, () => {
    const prefix = windowsInstall();
    assert.equal(browser._stable_lcu(`${prefix}\\releases\\0.9.5-aaaaaaaaaaaa`, 'Windows'), 'C:\\LCU\\lcu.cmd');
    assert.equal(browser._stable_lcu('C:/LCU/releases/0.9.5-aaaaaaaaaaaa', 'Windows'), 'C:\\LCU\\lcu.cmd');
    const home = 'C:\\Users\\u';
    const local = `${home}\\AppData\\Local`;
    const manifest = `${local}\\OpenAI\\extension\\com.openai.codexextension.json`;
    const env = { USERPROFILE: home, LOCALAPPDATA: local, NODE_REPL_NODE_PATH: 'C:\\node.exe' };
    const calls = [];
    let destinationSeen = null;
    const original = (command) => {
      calls.push(command);
      if (command[0] === 'reg.exe') return completed(0, `${manifest} REG_SZ ${manifest}`);
      const browsers = `${local}\\lcu\\browser`;
      const dir = readdirSync(host(browsers)).find((d) => statSync(join(host(browsers), d)).isDirectory());
      destinationSeen = `${browsers}\\${dir}`;
      write(manifest, JSON.stringify({ name: 'com.openai.codexextension',
        path: `${destinationSeen}\\chrome\\extension-host\\windows\\x64\\extension-host.exe` }));
      return completed(0);
    };
    patch({ environment: () => env, capture_run: original, run: original }, { USERPROFILE: home, LOCALAPPDATA: local });

    // 1. lcu browser install from the old release (generation A).
    const r1 = useRelease(prefix, '0.9.5-aaaaaaaaaaaa', A);
    const destination = browser.install(r1);
    assert.equal(destination, destinationSeen);
    assert.match(destination, /^C:\\Users\\u\\AppData\\Local\\lcu\\browser\\[0-9a-f]{16}$/);
    assert.equal(JSON.parse(readFileSync(host(manifest), 'utf8')).path, `${destination}\\lcu-native-host.cmd`);
    assert.equal(readFileSync(host(`${destination}\\lcu-native-host.cmd`), 'utf8'), WINDOWS_CMD('C:\\LCU\\lcu.cmd'));
    assert.equal(readFileSync(host(`${destination}\\.lcu-browser-host`), 'utf8'), `${prefix}\\apps\\${A}\\app\r\n`);
    assert.ok(calls[0].at(-1).startsWith('file:///C:/Users/u/AppData/Local/lcu/browser/'), calls[0].at(-1));

    // 2. An older (Python-era) wrapper; after updating to the new release (generation B), migration rewrites it
    //    because its owner marker names generation A of this prefix.
    writeFileSync(host(`${destination}\\lcu-native-host.cmd`), '@echo off\r\n"C:\\Python313\\python.exe" -B -u "%~dp0lcu-native-host.py" %*\r\n');
    const r2 = useRelease(prefix, '0.9.6-bbbbbbbbbbbb', B);
    assert.deepEqual(browser.migrate_relays(r2, home), [destination]);
    assert.equal(readFileSync(host(`${destination}\\lcu-native-host.cmd`), 'utf8'), WINDOWS_CMD('C:\\LCU\\lcu.cmd'));

    // 3. prune with a registration still pinned to A keeps A; once re-pinned to B, A goes. Output uses Windows paths.
    write(`${prefix}\\launcher-pins.json`, JSON.stringify({ registrations: { 'codex|user|': `c:\\lcu\\APPS\\${A.toUpperCase()}\\app\\resources\\cua_node\\bin\\node.exe` } }));
    let out = '';
    const real = io.stdout;
    io.stdout = (text) => { out += text; };
    try {
      maintenance.main(r2, ['--keep', '1', '--yes']);
      assert.ok(out.startsWith(`Keeping ${prefix}\\apps\\${A}: a registered agent launcher still runs its Node`), out);
      assert.ok(out.includes(`Removed ${prefix}\\releases\\0.9.5-aaaaaaaaaaaa (`), out);
      assert.deepEqual(new Set(readdirSync(host(`${prefix}\\apps`))), new Set([A, B]));
      write(`${prefix}\\launcher-pins.json`, JSON.stringify({ registrations: { 'codex|user|': `${prefix}\\apps\\${B}\\app\\resources\\cua_node\\bin\\node.exe` } }));
      out = '';
      maintenance.main(r2, ['--keep', '1', '--yes']);
      assert.ok(out.startsWith(`Removed ${prefix}\\apps\\${A} (`), out);
    } finally { io.stdout = real; }
    assert.deepEqual(readdirSync(host(`${prefix}\\apps`)), [B]);
    assert.deepEqual(readdirSync(host(`${prefix}\\releases`)), ['0.9.6-bbbbbbbbbbbb']);
    // The relay names only the stable command, so pruning A and the old release left it working.
    assert.equal(readFileSync(host(`${destination}\\lcu-native-host.cmd`), 'utf8'), WINDOWS_CMD('C:\\LCU\\lcu.cmd'));
  });
});

// Port of upstream 0.9.6 RefreshTests (tests/test_browser_setup.py, #22): `refresh` is the update-time path; it
// reuses `install` but only for a relay that is already ours. Node relay design: the launcher names the stable
// LCU command, so a relay CODE change alone needs no rewrite (Python copied the script and reported 'changed');
// the Python cases that changed lcu/native_host.py instead damage the launcher here.
describe('RefreshTests', () => {
  let base; let root; let home; let support; let chrome; let edge; let state;
  const STABLE = '/opt/lcu/current/bin/lcu';
  const pluginOf = (command) => dirname(dirname(fileURLToPath(command.at(-1))));
  const manifestOf = (browserDir) => join(support, browserDir, 'NativeMessagingHosts/com.openai.codexextension.json');

  beforeEach(() => {
    base = scratch();
    root = join(base, 'release');
    home = join(base, 'home');
    mkdirSync(home);
    support = join(home, 'Library/Application Support');
    const resources = join(root, 'app/Contents/Resources');
    const source = join(resources, 'plugins/openai-bundled/plugins/chrome');
    mkdirSync(join(source, 'scripts'), { recursive: true });
    writeFileSync(join(source, 'scripts/installManifest.mjs'), 'fixture');
    mkdirSync(join(source, 'extension-host/macos/arm64'), { recursive: true });
    writeFileSync(join(source, 'extension-host/macos/arm64/ChatGPT for Chrome'), 'fixture');
    releaseRelay(root);
    chrome = manifestOf('Google/Chrome');
    edge = manifestOf('Microsoft Edge');
    state = { fail: null, during: null, homes: [], nodePath: '/fake/node', calls: 0 };
    const env = { HOME: home, NODE_REPL_NODE_PATH: '/fake/node', CODEX_CLI_PATH: '/fake/codex', CUA_REPL_NODE_REPL_PATH: '/fake/repl' };
    // The upstream installer: writes every browser's manifest, under the HOME it is run with.
    const installer = (command, options) => {
      state.calls += 1;
      const plugin = pluginOf(command);
      writeFileSync(join(plugin, 'extension-host/macos/arm64/extension-host-config.json'), JSON.stringify({ nodePath: state.nodePath }));
      const runHome = options.env.HOME;
      state.homes.push(runHome);
      for (const browserDir of ['Google/Chrome', 'Microsoft Edge']) {
        const path = join(runHome, 'Library/Application Support', browserDir, 'NativeMessagingHosts/com.openai.codexextension.json');
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, JSON.stringify({ name: 'com.openai.codexextension', path: join(plugin, 'extension-host/macos/arm64/ChatGPT for Chrome') }));
      }
      if (state.during) state.during();
      return completed(state.fail ? 1 : 0, '', state.fail ?? '');
    };
    patch({ system: () => 'Darwin', paths: () => [join(root, 'app'), resources, null, {}], environment: () => env,
      capture_run: installer, stable_lcu: () => STABLE, geteuid: () => 501 }, { HOME: home });
    delete process.env.XDG_CONFIG_HOME;
    delete process.env.CHROME_CONFIG_HOME;
    delete process.env.XDG_DATA_HOME;
  });
  afterEach(restore);

  const tuple = (result) => [result[0], result[1], result[2]];
  const taken = JSON.stringify({ name: 'com.openai.codexextension', path: '/Applications/ChatGPT.app/host' });

  it('nothing is installed or changed when the connector was never set up', () => {
    assert.equal(browser.refresh(root)[0], 'absent');
    assert.equal(state.calls, 0);
    assert.equal(existsSync(join(support, 'lcu')), false);
    assert.equal(existsSync(chrome), false);
  });

  it('windows never set up does not resolve the app', () => {
    const local = join(base, 'win-empty/AppData/Local');
    patch({ system: () => 'Windows', paths: () => { throw new Error('resolved the app'); } },
      { USERPROFILE: dirname(dirname(local)), LOCALAPPDATA: local });
    assert.deepEqual(tuple(browser.refresh(root)), ['absent', null, []]);
    assert.equal(existsSync(local), false);
  });

  it('installed relay is refreshed and reports a change once', () => {
    const destination = browser.install(root);
    state.calls = 0;
    assert.deepEqual(tuple(browser.refresh(root)), ['unchanged', destination, []]);
    writeFileSync(join(destination, 'lcu-native-host'), '#!/bin/sh\n# an older wrapper\n');
    assert.deepEqual(tuple(browser.refresh(root)), ['changed', destination, []]);
    assert.equal(readFileSync(join(destination, 'lcu-native-host'), 'utf8'), POSIX_LAUNCHER(STABLE, destination));
    assert.equal(JSON.parse(readFileSync(chrome, 'utf8')).path, join(destination, 'lcu-native-host'));
    assert.equal(browser.refresh(root)[0], 'unchanged');
    assert.equal(state.calls, 3);
  });

  it('a relay implementation change alone is reported once as changed (upstream: the copied script changed)', () => {
    const destination = browser.install(root);
    assert.equal(browser.refresh(root).status, 'unchanged');
    writeFileSync(join(root, 'lcu/native_host.mjs'), `${readFileSync(join(root, 'lcu/native_host.mjs'), 'utf8')}\n// v2\n`);
    assert.deepEqual(tuple(browser.refresh(root)), ['changed', destination, []]);
    assert.equal(readFileSync(join(destination, '.lcu-relay-implementation'), 'utf8').trim(), browser._relay_implementation_digest(root));
    assert.equal(readFileSync(join(destination, 'lcu-native-host'), 'utf8'), POSIX_LAUNCHER(STABLE, destination)); // launcher as before
    assert.equal(browser.refresh(root).status, 'unchanged');
    writeFileSync(join(root, 'lcu/compat/pyerr_tables.mjs'), `${readFileSync(join(root, 'lcu/compat/pyerr_tables.mjs'), 'utf8')}\n// v2\n`);
    assert.equal(browser.refresh(root).status, 'changed'); // the import closure counts too
  });

  it('a Python-era relay (copied script) is rewritten to the Node launcher by a refresh', () => {
    const destination = browser.install(root);
    writeFileSync(join(destination, 'lcu-native-host'), '#!/usr/bin/env python3\n# relay\n');
    writeFileSync(join(destination, 'lcu-native-host.py'), '# copied relay\n');
    assert.equal(browser.refresh(root).status, 'changed');
    assert.equal(readFileSync(join(destination, 'lcu-native-host'), 'utf8'), POSIX_LAUNCHER(STABLE, destination));
  });

  it('a manifest that points elsewhere is reported and left alone', () => {
    const destination = browser.install(root);
    state.calls = 0;
    writeFileSync(chrome, taken);
    unlinkSync(edge);
    assert.deepEqual(tuple(browser.refresh(root)), ['elsewhere', destination, []]);
    assert.equal(readFileSync(chrome, 'utf8'), taken);
    assert.equal(state.calls, 0);
  });

  it('removed manifests are not recreated', () => {
    browser.install(root);
    state.calls = 0;
    unlinkSync(chrome);
    unlinkSync(edge);
    assert.equal(browser.refresh(root)[0], 'absent');
    assert.equal(existsSync(chrome), false);
    assert.equal(state.calls, 0);
  });

  it('other browsers are never written by a refresh', () => {
    browser.install(root);
    writeFileSync(edge, taken);
    const brave = manifestOf('BraveSoftware/Brave-Browser');
    state.homes = [];
    assert.equal(browser.refresh(root).status, 'unchanged');
    assert.equal(readFileSync(edge, 'utf8'), taken);
    assert.equal(existsSync(brave), false);
    assert.equal(state.homes.length, 1);
    assert.notEqual(state.homes[0], home); // the original installer ran against a scratch home
    assert.equal(existsSync(state.homes[0]), false); // and it is gone
  });

  it('a registration made by another installer during the refresh survives', () => {
    browser.install(root);
    writeFileSync(edge, '{"path": "/chatgpt/edge-host"}');
    const brave = manifestOf('BraveSoftware/Brave-Browser');
    state.during = () => {
      mkdirSync(dirname(brave), { recursive: true });
      writeFileSync(brave, '{"path": "/other/host"}');
      writeFileSync(edge, '{"path": "/other/edge-host"}');
    };
    assert.equal(browser.refresh(root).status, 'unchanged');
    assert.equal(readFileSync(brave, 'utf8'), '{"path": "/other/host"}');
    assert.equal(readFileSync(edge, 'utf8'), '{"path": "/other/edge-host"}');
  });

  it('a manifest of the relay that someone else changes during the refresh is not overwritten', () => {
    const destination = browser.install(root);
    unlinkSync(edge); // only Chrome is ours here; it is taken over while the installer runs
    state.during = () => writeFileSync(chrome, '{"path": "/chatgpt/host"}');
    assert.equal(browser.refresh(root).destination, destination);
    assert.equal(readFileSync(chrome, 'utf8'), '{"path": "/chatgpt/host"}');
    assert.equal(existsSync(edge), false);
  });

  it('a failed refresh does not take back a manifest changed meanwhile', () => {
    browser.install(root);
    state.during = () => writeFileSync(chrome, '{"path": "/chatgpt/host"}');
    state.fail = 'node crashed';
    assert.throws(() => browser.refresh(root), (e) => e.name === 'ValueError' && /installer failed/.test(e.message));
    assert.equal(readFileSync(chrome, 'utf8'), '{"path": "/chatgpt/host"}');
  });

  it('a failed refresh leaves the working registration and other manifests alone', () => {
    const destination = browser.install(root);
    writeFileSync(edge, taken);
    const before = readFileSync(chrome);
    state.fail = 'node crashed';
    assert.throws(() => browser.refresh(root), (e) => /installer failed/.test(e.message));
    assert.deepEqual(readFileSync(chrome), before);
    assert.equal(JSON.parse(readFileSync(chrome, 'utf8')).path, join(destination, 'lcu-native-host'));
    assert.equal(readFileSync(edge, 'utf8'), taken);
  });

  it('a browser that was not set up is not registered by a refresh', () => {
    browser.install(root);
    unlinkSync(edge);
    assert.equal(browser.refresh(root).status, 'unchanged');
    assert.equal(existsSync(edge), false);
  });

  it('a reclaimed chrome manifest is reported while another browser is refreshed', () => {
    const destination = browser.install(root);
    writeFileSync(chrome, taken);
    const result = browser.refresh(root);
    assert.deepEqual([result.status, result.destination, result.displaced], ['unchanged', destination, [chrome]]);
    assert.equal(readFileSync(chrome, 'utf8'), taken);
    assert.equal(JSON.parse(readFileSync(edge, 'utf8')).path, join(destination, 'lcu-native-host'));
  });

  it('a relay in a custom directory is found by its manifest', () => {
    const custom = join(base, 'custom-relay');
    browser.install(root, custom);
    writeFileSync(join(custom, 'lcu-native-host'), '#!/bin/sh\n# older\n');
    assert.deepEqual(tuple(browser.refresh(root)), ['changed', custom, []]);
    assert.equal(readFileSync(join(custom, 'lcu-native-host'), 'utf8'), POSIX_LAUNCHER(STABLE, custom));
    const data = join(support, 'lcu/browser');
    assert.ok(!(existsSync(data) && readdirSync(data).length));
  });

  it('a symlinked manifest of another owner is not written through', () => {
    browser.install(root);
    const target = join(base, 'someone-elses-file');
    writeFileSync(target, 'theirs');
    unlinkSync(edge);
    symlinkSync(target, edge);
    assert.equal(browser.refresh(root).status, 'unchanged');
    assert.equal(readFileSync(target, 'utf8'), 'theirs');
    assert.equal(lstatSync(edge).isSymbolicLink(), true);
  });

  it('linux does not recreate a removed registration', () => {
    const config = join(home, '.config');
    const linuxChrome = join(config, 'google-chrome/NativeMessagingHosts/com.openai.codexextension.json');
    const linuxEdge = join(config, 'microsoft-edge/NativeMessagingHosts/com.openai.codexextension.json');
    const plugin = join(root, 'app/resources/plugins/openai-bundled/plugins/chrome');
    mkdirSync(join(plugin, 'scripts'), { recursive: true });
    writeFileSync(join(plugin, 'scripts/installManifest.mjs'), 'fixture');
    const installer = (command, options) => {
      for (const browserDir of ['google-chrome', 'microsoft-edge']) {
        const path = join(options.env.HOME, '.config', browserDir, 'NativeMessagingHosts/com.openai.codexextension.json');
        mkdirSync(dirname(path), { recursive: true });
        writeFileSync(path, JSON.stringify({ path: join(pluginOf(command), 'extension-host/linux/x64/extension-host') }));
      }
      return completed(0);
    };
    patch({ system: () => 'Linux', paths: () => [join(root, 'app'), join(root, 'app/resources'), null, {}], capture_run: installer },
      { HOME: home, XDG_DATA_HOME: join(home, 'data') });
    browser.install(root);
    unlinkSync(linuxEdge);
    assert.equal(browser.refresh(root).status, 'unchanged');
    assert.equal(existsSync(linuxEdge), false);
    assert.ok(statSync(linuxChrome).isFile());
  });

  it('a repaired launcher permission asks to reconnect', { skip: skipOnWindows('status/refresh of the POSIX /bin/sh relay launcher of Linux and macOS (lcu-native-host, mode bits, sh); the Windows relay is the .cmd wrapper covered by the windows cases') }, () => {
    const destination = browser.install(root);
    chmodSync(join(destination, 'lcu-native-host'), 0o600);
    assert.equal(browser.refresh(root).status, 'changed');
    assert.equal(statSync(join(destination, 'lcu-native-host')).mode & 0o777, 0o700);
  });

  it('a change only in the host\'s runtime configuration asks to reconnect', () => {
    const destination = browser.install(root);
    assert.equal(browser.refresh(root).status, 'unchanged');
    state.nodePath = '/new/node';
    assert.deepEqual(tuple(browser.refresh(root)), ['changed', destination, []]);
    const config = join(destination, 'chrome/extension-host/macos/arm64/extension-host-config.json');
    assert.deepEqual(JSON.parse(readFileSync(config, 'utf8')), { nodePath: '/new/node' });
  });

  it('the active custom directory wins over a leftover default relay', () => {
    const defaultDir = browser.install(root);
    const custom = join(base, 'custom-relay');
    browser.install(root, custom);
    assert.equal(JSON.parse(readFileSync(chrome, 'utf8')).path, join(custom, 'lcu-native-host'));
    assert.deepEqual(tuple(browser.refresh(root)), ['unchanged', custom, []]);
    assert.equal(JSON.parse(readFileSync(chrome, 'utf8')).path, join(custom, 'lcu-native-host'));
    assert.ok(statSync(defaultDir).isDirectory());
  });

  it('root leaves the account alone', () => {
    const destination = browser.install(root);
    state.calls = 0;
    browser.hooks.geteuid = () => 0;
    assert.deepEqual(tuple(browser.refresh(root)), ['root', destination, []]);
    assert.equal(state.calls, 0);
  });

  it('sudo looks for the relay in the desktop account\'s home', () => {
    const destination = browser.install(root);
    state.calls = 0;
    const rootsHome = join(base, 'var-root');
    mkdirSync(rootsHome);
    browser.hooks.geteuid = () => 0;
    process.env.HOME = rootsHome;
    process.env.SUDO_USER = 'desktop';
    browser.hooks.getpwnam = (name) => {
      if (name === 'desktop') return { pw_dir: home };
      const error = new Error(`getpwnam(): name not found: '${name}'`);
      error.name = 'KeyError';
      throw error;
    };
    assert.deepEqual(tuple(browser.refresh(root)), ['root', destination, []]);
    process.env.SUDO_USER = 'nobody-here';
    assert.equal(browser.refresh(root).status, 'absent');
    assert.equal(state.calls, 0);
  });

  it('windows relay is refreshed and follows a replaced app generation', () => {
    // Windows-labelled with host (POSIX) paths, as upstream's test; the native-path case is covered above.
    const win = join(base, 'win');
    const winRoot = join(win, 'prefix/releases/r1');
    const generations = {};
    for (const name of ['gen1', 'gen2']) {
      const app = join(win, 'prefix/apps', name, 'app');
      const plugin = join(app, 'resources/plugins/openai-bundled/plugins/chrome');
      mkdirSync(join(plugin, 'scripts'), { recursive: true });
      writeFileSync(join(plugin, 'scripts/installManifest.mjs'), 'fixture');
      mkdirSync(join(plugin, 'extension-host/windows/x64'), { recursive: true });
      writeFileSync(join(plugin, 'extension-host/windows/x64/extension-host.exe'), 'fixture');
      generations[name] = [app, join(app, 'resources'), null, {}];
    }
    releaseRelay(winRoot);
    const winHome = join(win, 'account');
    const local = join(winHome, 'AppData/Local');
    const manifest = join(local, 'OpenAI/extension/com.openai.codexextension.json');
    const env = { USERPROFILE: winHome, LOCALAPPDATA: local, NODE_REPL_NODE_PATH: 'C:/node.exe' };
    const registered = { value: null };
    const installs = [];
    const failing = { on: false };
    let selected = generations.gen1;
    const installer = (command) => {
      if (command[0] === 'reg.exe') {
        return completed(0, `\r\nHKEY_CURRENT_USER\\...\r\n    (Default)    REG_SZ    ${registered.value ?? manifest}\r\n`);
      }
      installs.push(command);
      mkdirSync(dirname(manifest), { recursive: true });
      writeFileSync(manifest, JSON.stringify({ name: 'com.openai.codexextension', path: join(pluginOf(command), 'extension-host/windows/x64/extension-host.exe') }));
      return completed(failing.on ? 1 : 0);
    };
    patch({ system: () => 'Windows', paths: () => selected, environment: () => env, capture_run: installer, run: installer,
      stable_lcu: () => 'C:\\LCU\\lcu.cmd' }, { USERPROFILE: winHome, LOCALAPPDATA: local });
    assert.deepEqual(tuple(browser.refresh(winRoot)), ['absent', null, []]);
    const destination = browser.install(winRoot);
    assert.deepEqual(tuple(browser.refresh(winRoot)), ['unchanged', destination, []]);
    writeFileSync(join(destination, 'lcu-native-host.cmd'), '@echo off\r\n"C:\\Python313\\python.exe" -B -u "%~dp0lcu-native-host.py" %*\r\n');
    assert.deepEqual(tuple(browser.refresh(winRoot)), ['changed', destination, []]);
    assert.equal(readFileSync(join(destination, 'lcu-native-host.cmd'), 'utf8'), WINDOWS_CMD('C:\\LCU\\lcu.cmd'));
    assert.equal(JSON.parse(readFileSync(manifest, 'utf8')).path, join(destination, 'lcu-native-host.cmd'));
    // A failing original installer has already rewritten the manifest; the working registration comes back.
    failing.on = true;
    const working = readFileSync(manifest, 'utf8');
    assert.throws(() => browser.refresh(winRoot), (e) => /installer failed/.test(e.message));
    assert.equal(readFileSync(manifest, 'utf8'), working);
    failing.on = false;
    // The Store app changed: the update's installer made a new private generation.
    selected = generations.gen2;
    const ours = readFileSync(manifest, 'utf8');
    writeFileSync(manifest, JSON.stringify({ path: 'C:\\ChatGPT\\extension-host.exe' }));
    assert.equal(browser.refresh(winRoot).status, 'elsewhere'); // reclaimed; the old generation's relay is still known
    writeFileSync(manifest, ours);
    const moved = browser.refresh(winRoot);
    assert.equal(moved.status, 'changed');
    assert.notEqual(moved.destination, destination);
    assert.equal(readFileSync(join(moved.destination, '.lcu-browser-host'), 'utf8'), `${generations.gen2[0]}${process.platform === 'win32' ? '\r\n' : '\n'}`); // text mode
    assert.equal(JSON.parse(readFileSync(manifest, 'utf8')).path, join(moved.destination, 'lcu-native-host.cmd'));
    assert.deepEqual(tuple(browser.refresh(winRoot)), ['unchanged', moved.destination, []]);
    writeFileSync(manifest, JSON.stringify({ path: 'C:\\ChatGPT\\extension-host.exe' }));
    assert.deepEqual(tuple(browser.refresh(winRoot)), ['elsewhere', moved.destination, []]);
    writeFileSync(manifest, JSON.stringify({ path: join(moved.destination, 'lcu-native-host.cmd') }));
    registered.value = `${manifest}.backup`; // another owner's entry that only starts with our path
    const calls = installs.length;
    assert.deepEqual(tuple(browser.refresh(winRoot)), ['elsewhere', moved.destination, []]);
    assert.equal(installs.length, calls);
  });
});
