"""Generate bin/{lcu,lcu-session,lcu-codex-sandbox} from lcu/shim/common.sh and the per-launcher parts.

    python3 tests/node/generate_shims.py           # rewrite the launchers
    python3 tests/node/generate_shims.py --check   # exit 1 when a launcher differs from what it would generate

Developer tool (not shipped). tests/node/entry.test.mjs runs --check, and also checks that every
`# BEGIN LCU COMMON` block in the repository (scripts/install.sh.node included) equals lcu/shim/common.sh.
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
COMMON = (ROOT / 'lcu/shim/common.sh').read_text()

HEAD = """#!/bin/sh -p
# LCU {name} launcher: runs lcu/entry.mjs on the ChatGPT app's bundled Node, never a Node found on PATH.
# `-p`: bash (macOS /bin/sh) then ignores SHELLOPTS, BASHOPTS, CDPATH, ENV/BASH_ENV and exported functions; dash
# reads none of them in a script. The LCU COMMON block is lcu/shim/common.sh verbatim (tests/node/entry.test.mjs);
# generated by tests/node/generate_shims.py. See .port/notes/entry.md.
set -f
__LCU_CLI={cli}
__LCU_PREFIX='{prefix}'

"""

HELP = """# `lcu --help` must work while the app's Node is unusable: the same text runtime.mjs prints (USAGE + HELP_SUFFIX;
# tests/node/entry.test.mjs compares them). Python's rule: a first --help/-h, or exactly --help/-h after the
# leading --chrome/--audio registration options (each at most once).
__lcu_static_help() {
  case ${1-} in --help|-h) __lcu_print_help; exit 0 ;; esac
  __LCU_HC=
  __LCU_HA=
  while [ $# -gt 0 ]; do
    case $1 in
      --chrome) [ -z "$__LCU_HC" ] || break; __LCU_HC=1; shift ;;
      --audio) [ -z "$__LCU_HA" ] || break; __LCU_HA=1; shift ;;
      *) break ;;
    esac
  done
  if [ $# -eq 1 ]; then
    case $1 in --help|-h) __lcu_print_help; exit 0 ;; esac
  fi
}
__lcu_print_help() {
  printf '%s\\n' 'Usage: lcu [--chrome] [--audio] [--mcp-discovery-compat]
       lcu setup OPTIONS
       lcu browser install
       lcu browser status
       lcu apps [list|allow APP|revoke APP] [--json]   (macOS)
       lcu origins [list [--session ID] [--json]]
       lcu origins forget ORIGIN [--session ID | --all-sessions] [--allowed | --denied]
       lcu prune [--keep N] [--yes]
       lcu update [--check [--json]] [--yes]
       lcu doctor
       lcu status [--json]
       lcu --version
With no arguments, starts the original computer-use stdio MCP server. `lcu --chrome` also enables its browser surface; `lcu setup --chrome` registers that command. `lcu --audio` enables the original optional computer-audio API; `lcu setup --audio` registers that command.'
}

"""

NO_HELP = """__lcu_static_help() { :; }

"""

LAUNCH = """
# Launch: resolve this release, gate its Node, quarantine Node's startup inputs, exec the entry module.
__lcu_unusable() {
  if [ "$__LCU_CLI" = lcu ]; then __lcu_static_help "$@"; fi
  printf '%sCannot run the ChatGPT app'"'"'s bundled Node (%s): %s. Repair the official app and rerun the LCU installer.\\n' \\
    "$__LCU_PREFIX" "${__LCU_NODE-}" "$__LCU_REASON" >&2
  exit 1
}

__lcu_launch() {
  __LCU_NODE=
  __lcu_tools || __lcu_unusable "$@"
  if ! __lcu_self_root; then
    printf '%s%s\\n' "$__LCU_PREFIX" "$__LCU_REASON" >&2
    exit 1
  fi
  __LCU_NODE=$__LCU_ROOT/agent-tools/node/bin/node
  if [ ! -e "$__LCU_NODE" ]; then
    __LCU_REASON='it is missing'
    __lcu_unusable "$@"
  fi
  # The release's `app` link is the selected application (installation.json names the same app).
  __lcu_gate "$__LCU_NODE" "$__LCU_ROOT/app" 0 || __lcu_unusable "$@"
  __lcu_quarantine
  __lcu_signals
  __lcu_bytes_check "$@"
  __LCU_ARGV0=$0
  export __LCU_ARGV0
  # The physical path the gate verified, never the release alias again (review port-runtime #1).
  exec "$__LCU_REAL" --disable-warning=ExperimentalWarning "$__LCU_ROOT/lcu/entry.mjs" "$__LCU_CLI" "$@"
}

__lcu_launch "$@"
"""

LAUNCHERS = (('lcu', 'lcu', 'LCU: '), ('lcu-session', 'session', 'LCU session: '),
             ('lcu-codex-sandbox', 'sandbox', 'LCU: '))


def generate(name, cli, prefix):
    return HEAD.format(name=name, cli=cli, prefix=prefix) + (HELP if cli == 'lcu' else NO_HELP) + COMMON + LAUNCH


def main(argv):
    check = argv == ['--check']
    stale = []
    for name, cli, prefix in LAUNCHERS:
        path = ROOT / 'bin' / name
        text = generate(name, cli, prefix)
        if check:
            if not path.is_file() or path.read_text() != text:
                stale.append(name)
        else:
            path.write_text(text)
            path.chmod(0o755)
    if stale:
        print('stale launchers (run tests/node/generate_shims.py): ' + ', '.join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1:]))
