// Port of tests/test_harness_setup.py, calling lcu/harness_setup.mjs directly (the Python cases go through
// setup.configure, which catches the error into a failures list; here the same error is asserted as thrown).
// detect/validate cases belong to the setup port (see .port/notes/harness_setup.md).
import assert from 'node:assert/strict';
import {
  chmodSync, existsSync, mkdirSync, readFileSync, readdirSync, realpathSync, statSync, symlinkSync, writeFileSync,
} from 'node:fs';
import { resolve } from 'node:path';
import test from 'node:test';

import { lcu, tempdir, nat } from './p4_support.mjs';
import { skipOnWindows } from './windows_skip.mjs';

const harness = await lcu('harness_setup');

function walk(root, prefix = '') {
  const out = {};
  for (const entry of readdirSync(`${root}/${prefix}`, { withFileTypes: true })) {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isDirectory()) Object.assign(out, walk(root, relative));
    else if (statSync(`${root}/${relative}`).isFile()) out[relative] = readFileSync(`${root}/${relative}`).toString('hex');
  }
  return out;
}

function fixture(t) {
  const root = tempdir(t);
  const home = nat(`${root}/home`);
  mkdirSync(home);
  const project = nat(`${root}/project with spaces`);
  mkdirSync(project);
  const release = nat(`${root}/release`);
  mkdirSync(nat(`${release}/adapters/pi`), { recursive: true });
  writeFileSync(nat(`${release}/adapters/pi/index.ts`), 'export default function () {}');
  mkdirSync(nat(`${release}/adapters/hermes`));
  for (const name of ['plugin.yaml', '__init__.py', 'bridge.mjs']) writeFileSync(`${release}/adapters/hermes/${name}`, 'fixture ' + name);
  const state = { command: ['/opt/lcu/current/bin/lcu', '--audio', '--chrome'] };
  const ok = (argv) => ({ args: argv, returncode: 0, stdout: '', stderr: '' });
  const configure = (name, { scope = 'user', run = ok, executable = '/bin/omp', env = {} } = {}) => {
    const saved = { ...harness.internals };
    Object.assign(harness.internals, { which: () => executable, run });
    try {
      const environ = { PATH: '/bin', HOME: home, ...env };
      const options = { scope, project: scope === 'project' ? project : null, env: environ };
      if (name === 'omp') return harness.configure_omp(home, state.command, release, options);
      return harness.configure_hermes(home, state.command, '/original/node', release, options);
    } finally {
      Object.assign(harness.internals, saved);
    }
  };
  return { root, home, project, release, state, configure };
}

test('omp native link preserves scope and command without a skill', (t) => {
  const { home, project, release, state, configure } = fixture(t);
  const calls = [];
  const run = (argv, options) => {
    calls.push([argv, options]);
    return { args: argv, returncode: 0, stdout: '', stderr: '' };
  };
  for (const profile of ['blue', 'green']) {
    configure('omp', { run, env: { OMP_PROFILE: profile } });
    const [argv, options] = calls.at(-1);
    assert.deepEqual(argv.slice(0, 3), ['/bin/omp', 'plugin', 'link']);
    const pkg = argv[3];
    const manifest = JSON.parse(readFileSync(nat(`${pkg}/package.json`), 'utf8'));
    assert.deepEqual(manifest.omp.extensions, ['./index.ts']);
    const wrapper = readFileSync(nat(`${pkg}/index.ts`), 'utf8');
    const specifier = JSON.parse(wrapper.split('import lcu from ')[1].split(';')[0]);
    assert.ok(specifier.startsWith('.'));
    assert.equal(realpathSync(resolve(pkg, specifier)), nat(`${release}/adapters/pi/index.ts`));
    assert.ok(wrapper.includes('["/opt/lcu/current/bin/lcu", "--audio", "--chrome"]'));
    assert.ok(wrapper.includes('connectOnLoad: true'));
    assert.ok(wrapper.includes('ompEssentialTools: true'));
    assert.equal(existsSync(nat(`${pkg}/skills`)), false);
    assert.equal(options.cwd, home);
    assert.equal(options.env.HOME, home);
    assert.equal(options.timeout, 120000);
    assert.equal(options.stdin, 'devnull');
    // Exact generated bytes (Python json.dumps(manifest, indent=2) + '\n'; the ownership marker).
    assert.equal(readFileSync(nat(`${pkg}/package.json`), 'utf8'),
      '{\n  "name": "lcu-computer-use",\n  "version": "0.1.0",\n  "private": true,\n  "type": "module",\n' +
      '  "omp": {\n    "extensions": [\n      "./index.ts"\n    ]\n  }\n}\n');
    assert.equal(readFileSync(nat(`${pkg}/.lcu-generated.json`), 'utf8'), '{"harness": "omp"}\n');
  }
  assert.notEqual(calls[0][0].at(-1), calls[1][0].at(-1));
  assert.equal(existsSync(nat(`${project}/.pi`)), false);
  void state;
});

test('omp package path is the Python sha256 identity', (t) => {
  const { home, configure } = fixture(t);
  const calls = [];
  configure('omp', { run: (argv) => { calls.push(argv); return { returncode: 0, stdout: '', stderr: '' }; }, env: { OMP_PROFILE: 'blue' } });
  // hashlib.sha256(json.dumps(['user', '', 'blue', '', '']).encode()).hexdigest()[:16]
  assert.equal(calls[0][3], nat(process.platform === 'win32' ? `${home}/AppData/Local/LCU/omp/user-718432fd3a1cf177`
    : `${home}/.local/share/lcu/omp/user-718432fd3a1cf177`));
});

test('omp rejects project scope without installing globally', (t) => {
  const { home, configure } = fixture(t);
  const calls = [];
  assert.throws(() => configure('omp', { scope: 'project', run: (...args) => calls.push(args) }),
    { name: 'ValueError', message: /project scope is not supported/ });
  assert.deepEqual(calls, []);
  assert.equal(existsSync(nat(`${home}/.local/share/lcu/omp`)), false);
});

test('missing omp fails without creating a package', (t) => {
  const { home, configure } = fixture(t);
  assert.throws(() => configure('omp', { executable: null }), { name: 'ValueError', message: /not on the target account PATH/ });
  assert.equal(existsSync(nat(`${home}/.local/share/lcu/omp`)), false);
});

test('omp installer failure is reported', (t) => {
  const { configure } = fixture(t);
  assert.throws(() => configure('omp', { run: (argv) => ({ args: argv, returncode: 9, stdout: '', stderr: 'plugin failed' }) }),
    { name: 'ValueError', message: 'installer exited 9: plugin failed' });
});

test('hermes registers local plugin and command without a skill', (t) => {
  const { home, release, state, configure } = fixture(t);
  const calls = [];
  configure('hermes', { executable: '/bin/hermes', run: (argv, options) => { calls.push([argv, options]); return { returncode: 0, stdout: '', stderr: '' }; } });
  assert.deepEqual(calls[0][0], ['/bin/hermes', 'plugins', 'enable', 'lcu-cua']);
  assert.equal(calls[0][1].env.HERMES_HOME, nat(`${home}/.hermes`));
  const pkg = nat(`${home}/.hermes/plugins/lcu-cua`);
  assert.deepEqual(JSON.parse(readFileSync(nat(`${pkg}/lcu-config.json`), 'utf8')), {
    command: state.command, node: '/original/node', bridge: nat(`${release}/adapters/hermes/bridge.mjs`),
  });
  assert.equal(existsSync(nat(`${pkg}/skills`)), false);
});

test('hermes rejects project scope without installing globally', (t) => {
  const { home, configure } = fixture(t);
  assert.throws(() => configure('hermes', { scope: 'project', executable: '/bin/hermes' }),
    { name: 'ValueError', message: /project scope is not supported/ });
  assert.equal(existsSync(nat(`${home}/.hermes`)), false);
});

test('hermes explicit profile owns both plugin and enable', (t) => {
  const { root, home, configure } = fixture(t);
  const profile = nat(`${root}/custom hermes profile`);
  const calls = [];
  configure('hermes', { executable: '/bin/hermes', env: { HERMES_HOME: profile }, run: (argv, options) => { calls.push(options); return { returncode: 0, stdout: '', stderr: '' }; } });
  assert.ok(statSync(nat(`${profile}/plugins/lcu-cua/lcu-config.json`)).isFile());
  assert.equal(calls[0].env.HERMES_HOME, profile);
  assert.equal(existsSync(nat(`${home}/.hermes`)), false);
});

test('profile paths must be absolute (hermes)', (t) => {
  const { configure } = fixture(t);
  assert.throws(() => configure('hermes', { env: { HERMES_HOME: 'relative/profile' } }), { name: 'ValueError', message: /must be absolute/ });
});

test('hermes plugin symlink is never followed', (t) => {
  const { root, home, configure } = fixture(t);
  const plugins = nat(`${home}/.hermes/plugins`);
  mkdirSync(plugins, { recursive: true });
  const other = nat(`${root}/other-plugin`);
  mkdirSync(other);
  writeFileSync(nat(`${other}/keep.txt`), 'untouched');
  symlinkSync(other, nat(`${plugins}/lcu-cua`));
  assert.throws(() => configure('hermes', { executable: '/bin/hermes' }), { name: 'ValueError', message: /symlink/ });
  assert.equal(readFileSync(nat(`${other}/keep.txt`), 'utf8'), 'untouched');
});

test('registration refuses an unowned plugin directory', (t) => {
  const { home, configure } = fixture(t);
  const pkg = nat(`${home}/.hermes/plugins/lcu-cua`);
  mkdirSync(pkg, { recursive: true });
  writeFileSync(nat(`${pkg}/__init__.py`), 'user plugin');
  assert.throws(() => configure('hermes', { executable: '/bin/hermes' }), { name: 'ValueError', message: /unowned plugin directory/ });
  assert.equal(readFileSync(nat(`${pkg}/__init__.py`), 'utf8'), 'user plugin');
});

test('failed reinstallation restores previous package', (t) => {
  const { home, state, configure } = fixture(t);
  configure('hermes', { executable: '/bin/hermes' });
  const pkg = nat(`${home}/.hermes/plugins/lcu-cua`);
  const previous = walk(pkg);
  state.command = ['/changed/runtime'];
  assert.throws(() => configure('hermes', { executable: '/bin/hermes', run: (argv) => ({ args: argv, returncode: 1, stdout: '', stderr: 'enable failed' }) }),
    { message: /enable failed/ });
  assert.deepEqual(walk(pkg), previous);
  // No staging directory is left beside the package.
  assert.deepEqual(readdirSync(nat(`${home}/.hermes/plugins`)), ['lcu-cua']);
});

test('failed package swap restores previous package', (t) => {
  const { home, configure } = fixture(t);
  configure('hermes', { executable: '/bin/hermes' });
  const pkg = nat(`${home}/.hermes/plugins/lcu-cua`);
  const previous = readFileSync(nat(`${pkg}/lcu-config.json`));
  const saved = harness.internals.replace;
  harness.internals.replace = (source, target) => {
    if (source.split(/[\\/]/).at(-1) === 'next') throw new Error('fixture rename failure');
    return saved(source, target);
  };
  try {
    assert.throws(() => configure('hermes', { executable: '/bin/hermes' }), { message: /fixture rename failure/ });
  } finally {
    harness.internals.replace = saved;
  }
  assert.deepEqual(readFileSync(nat(`${pkg}/lcu-config.json`)), previous);
});

// ------------------------------------------------------------------------------------------- review P2-3, P3-9, P2-4
function withInternals(replacements, body) {
  const saved = { ...harness.internals };
  Object.assign(harness.internals, replacements);
  try {
    return body();
  } finally {
    Object.assign(harness.internals, saved);
  }
}

test('an installer without a #! line fails like execve, never runs, and the package is rolled back', { skip: skipOnWindows('the fake omp installer is a #! shell script (execve/ENOEXEC and /bin/sh text-mode output); Windows runs omp.exe') }, (t) => {
  const { root, home, release, state } = fixture(t);
  const omp = nat(`${root}/omp`);
  writeFileSync(omp, `touch '${root}/ran'\n`);
  chmodSync(omp, 0o755);
  assert.throws(() => withInternals({ which: () => omp }, () => harness.configure_omp(home, state.command, release,
    { scope: 'user', project: null, env: { PATH: '/bin', HOME: home } })), { message: `[Errno 8] Exec format error: '${omp}'` });
  assert.equal(existsSync(nat(`${root}/ran`)), false);
  assert.deepEqual(readdirSync(nat(`${home}/.local/share/lcu/omp`)), []);
});

test('installer diagnostics get Python text-mode newlines', { skip: skipOnWindows('the fake omp installer is a #! shell script (execve/ENOEXEC and /bin/sh text-mode output); Windows runs omp.exe') }, (t) => {
  const { root, home, release, state } = fixture(t);
  const omp = nat(`${root}/omp`);
  writeFileSync(omp, "#!/bin/sh\nprintf 'line1\\r\\nline2\\rline3\\n' >&2\nexit 9\n");
  chmodSync(omp, 0o755);
  assert.throws(() => withInternals({ which: () => omp }, () => harness.configure_omp(home, state.command, release,
    { scope: 'user', project: null, env: { PATH: '/bin', HOME: home } })), { message: 'installer exited 9: line1\nline2\nline3' });
});

test('Windows paths: drive-absolute HERMES_HOME, rooted-only and relative profiles (fixture, no live Windows)', () => {
  withInternals({ platform: 'win32', which: () => 'C:\\bin\\hermes.exe' }, () => {
    const call = (profile) => harness.configure_hermes('C:\\Users\\fixture', ['lcu'], 'C:\\node.exe', 'C:\\lcu',
      { scope: 'user', project: null, env: { PATH: 'C:\\bin', HERMES_HOME: profile } });
    // Accepted as absolute: fails only later, at the (absent) release files, with WindowsPath joins.
    assert.throws(() => call('C:\\profiles\\hermes'), { message: 'LCU Hermes plugin missing: C:\\lcu\\adapters\\hermes\\plugin.yaml' });
    assert.throws(() => call('\\\\server\\share\\hermes'), { message: /^LCU Hermes plugin missing/ });
    for (const profile of ['\\profiles\\hermes', 'profiles\\hermes', 'C:profiles']) {
      assert.throws(() => call(profile), { message: 'HERMES_HOME must be absolute.' });
    }
  });
});

test('Windows paths: OMP refuses a release on another drive (fixture, no live Windows)', () => {
  withInternals({ platform: 'win32', which: () => 'C:\\bin\\omp.exe', is_file: () => true }, () => {
    assert.throws(() => harness.configure_omp('D:\\Users\\fixture', ['lcu'], 'C:\\lcu',
      { scope: 'user', project: null, env: { PATH: 'C:\\bin' } }),
    { name: 'ValueError', message: 'OMP requires its generated plugin and the LCU release on the same filesystem drive.' });
  });
});
